"""Plain-Python string builders for generated TypeScript -- no templating."""

from __future__ import annotations
from dataclasses import dataclass, field

HEADER = "// AUTO-GENERATED by mex_form_codegen -- do not edit by hand."


def doc_comment(text: str | None) -> str:
    return f"/** {text} */\n" if text else ""


def indent(lines: list[str], levels: int = 1) -> list[str]:
    p = "  " * levels
    return [f"{p}{l}" for l in lines]


def render_function(
    name: str, path_type: str, body: list[str], doc: str | None = None
) -> str:
    lines = [
        f"{doc_comment(doc)}export function {name}(path: SchemaPath<{path_type}>): void {{",
        *indent(body),
        "}\n",
    ]
    return "\n".join(lines) + "\n"


def render_tree_aggregator(name: str, calls: list[str], doc: str | None = None) -> str:
    lines = [
        f"{doc_comment(doc)}export function validate{name}(path: SchemaPathTree<{name}>): void {{",
        *indent(calls),
        "}\n",
    ]
    return "\n".join(lines) + "\n"


def render_forgiving_aggregator(
    name: str, primary_fn: str, calls: list[str], doc: str | None = None
) -> str:
    lines = [
        f"{doc_comment(doc)}export function validate{name}(path: SchemaPath<{name} | string>): void {{",
        "  applyWhenValue(path, (value): value is string => typeof value === 'string', (path) => {",
        f"    {primary_fn}(path);",
        "  });",
        f"  applyWhenValue(path, (value): value is {name} => typeof value !== 'string', (path) => {{",
        *indent(calls, 2),
        "  });",
        "}\n",
    ]
    return "\n".join(lines) + "\n"


def render_enum_validator(
    name: str, quoted_values: list[str], doc: str | None = None
) -> str:
    lines = [
        f"{doc_comment(doc)}export function validate{name}(path: SchemaPath<string>): void {{",
        f"  enumValidator(path, [{', '.join(quoted_values)}], 'enum');",
        "}\n",
    ]
    return "\n".join(lines) + "\n"


def render_interface(
    name: str, fields: list[dict], extends: str | None = None, doc: str | None = None
) -> str:
    header = (
        f"export interface {name}" + (f" extends {extends}" if extends else "") + " {"
    )
    lines = [f"{doc_comment(doc)}{header}"]
    for f in fields:
        if f.get("doc"):
            lines.append(f"  /** {f['doc']} */")
        lines.append(f"  {f['name']}{'?' if f['optional'] else ''}: {f['ts_type']};")
    lines.append("}\n")
    return "\n".join(lines) + "\n"


def render_type_alias(name: str, values: list[str], doc: str | None = None) -> str:
    return f"{doc_comment(doc)}export type {name} = {' | '.join(values)};\n\n"


_ANY_OF = """\
export function anyOfPatternValidator(
  path: SchemaPath<string>,
  candidatePatterns: string[],
  message: string,
  required = false,
): void {
  validate(path, (ctx) => {
    const value = ctx.value();
    if (value == null || value === '') {
      return required ? { kind: message, message } : null;
    }
    const matches = candidatePatterns.some((p) => new RegExp(p).test(value));
    return matches ? null : { kind: message, message };
  });
}
"""

_ENUM = """\
export function enumValidator(
  path: SchemaPath<string>,
  allowed: readonly string[],
  message: string,
): void {
  validate(path, (ctx) => {
    const value = ctx.value();
    return allowed.includes(value) ? null : { kind: message, message };
  });
}
"""


def render_runtime_helpers(*, any_of_pattern: bool, enum: bool) -> str:
    parts = ["// -- Validators @angular/forms/signals doesn't ship out of the box --\n"]
    if any_of_pattern:
        parts.append(_ANY_OF)
    if enum:
        parts.append(_ENUM)
    return "\n".join(parts)


@dataclass
class TSFile:
    import_lines: list[str] = field(default_factory=list)
    prelude: str = ""
    body_parts: list[str] = field(default_factory=list)

    def render(self) -> str:
        sections = [HEADER, *self.import_lines, ""]
        if self.prelude:
            sections += [self.prelude, ""]
        sections.append("".join(self.body_parts).rstrip("\n"))
        return "\n".join(sections) + "\n"
