import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

from mex.common.logging import logger
from mex.editor.code_gen.collection import build_schema_index
from mex.editor.code_gen.patterns import PatternRegistry
from mex.editor.code_gen.zod_expressions import jsdoc, render_zod_schema

if TYPE_CHECKING:
    from mex.editor.code_gen.models import Bundle, SchemaIndex, ZodResult

SUFFIX = ".ts"
ESLINT_DISABLE = "/* eslint-disable @typescript-eslint/naming-convention */"
HEADER = "// AUTO-GENERATED by `generate-ts-models` -- do not edit by hand."


def kebab(name: str) -> str:
    """PascalCase/camelCase -> kebab-case, Angular's file-naming default.

    For example `ExtractedActivity` -> `extracted-activity`.
    """
    return re.sub(r"(?<!^)(?=[A-Z])", "-", name).lower()


def import_specifier(to_name: str) -> str:
    """Relative TS import specifier for `to_name`'s file, e.g. `./shared`.

    Every output file sits directly in the output root (see the module
    docstring), so this is always a sibling import. The leading `./` matters:
    without it the specifier would be a bare/node_modules import.
    """
    return f"./{kebab(to_name)}"


def _write(output_dir: Path, name: str, body: str) -> Path:
    """Write one generated file, header and all, and return its path."""
    text = f"{ESLINT_DISABLE}\n{HEADER}\n\n{body}"
    path = output_dir / Path(kebab(name)).with_suffix(SUFFIX)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    return path


def _topo_order(names: list[str], deps: dict[str, set[str]]) -> list[str]:
    """Order `names` so every name comes after the names it depends on.

    Only dependencies within `names` count; ties break alphabetically, for a
    deterministic diff between runs. Prevents "used before declared" for
    same-file `const` references (see module docstring).

    Raises:
        ValueError: if the defs in one file reference each other cyclically.
            No ordering can satisfy that, and emitting the forward reference
            anyway would write a file that throws on import -- Zod needs an
            explicit `z.lazy()` for recursive schemas, which this generator
            does not emit.
    """
    names_set, seen, order = set(names), set(), []

    def visit(n: str, stack: tuple[str, ...]) -> None:
        if n in seen:
            return
        if n in stack:
            cycle = " -> ".join((*stack[stack.index(n) :], n))
            msg = (
                f"Cyclic schema reference: {cycle}. JavaScript `const` bindings "
                f"are not hoisted, so this cannot be emitted as a flat file; "
                f"recursive schemas need z.lazy(), which is not supported yet."
            )
            raise ValueError(msg)
        for dep in sorted(deps.get(n, set()) & names_set):
            visit(dep, (*stack, n))
        seen.add(n)
        order.append(n)

    for n in sorted(names):
        visit(n, ())
    return order


@dataclass(frozen=True)
class _Context:
    """The state every output file is rendered against."""

    index: SchemaIndex
    shared: set[str]
    results: dict[str, ZodResult]
    patterns: PatternRegistry
    output_dir: Path

    def loc(self, name: str) -> str:
        """The file that declares `name`'s schema.

        That is the shared file if `name` is used by >1 bundle, otherwise its
        one owning bundle's single file. Not shared means used by exactly one
        bundle: every def in the index got there by being walked from some
        bundle's roots.
        """
        if name in self.shared:
            return "shared"
        return self.index.owning_bundle(name) or "shared"


def _write_def_file(
    ctx: _Context,
    file_name: str,
    def_names: list[str],
    declare_patterns: set[str],
) -> Path:
    """Write one file containing zero or more defs plus the imports they need.

    Defs are topologically ordered so same-file references never point forward.
    """
    results = ctx.results
    def_names = _topo_order(def_names, {n: results[n].def_refs for n in def_names})
    local = set(def_names)
    refs: set[str] = set()
    pattern_names: set[str] = set()
    for n in def_names:
        refs |= results[n].def_refs
        pattern_names |= results[n].pattern_names

    by_specifier: dict[str, set[str]] = {}
    if pattern_names and not declare_patterns:
        by_specifier.setdefault(import_specifier("shared"), set()).update(pattern_names)
    for ref in refs - local:
        by_specifier.setdefault(import_specifier(ctx.loc(ref)), set()).add(
            f"{ref}Schema"
        )

    imports = ['import { z } from "zod";']
    for spec, names in sorted(by_specifier.items()):
        imports.append(f'import {{ {", ".join(sorted(names))} }} from "{spec}";')

    pattern_doc = jsdoc("Regex pattern (deduplicated across every bundle).")
    body_parts = []
    if declare_patterns:
        lines = [
            f"{pattern_doc}export const {n} = {json.dumps(p)};\n"
            for p, n in ctx.patterns.all_patterns().items()
            if n in declare_patterns
        ]
        body_parts.append("\n".join(lines) + "\n")
    body_parts += [results[n].code for n in def_names]

    return _write(
        ctx.output_dir, file_name, "\n".join(imports) + "\n\n" + "".join(body_parts)
    )


def generate_zod_schemas(bundles: list[Bundle], output_dir: str | Path) -> list[Path]:
    """Generate `shared.ts` plus one `{bundle}.ts` per bundle, and return the paths.

    Everything lands flat under `output_dir`, no subfolders:

        shared.ts     # patterns + schemas for defs used by >1 bundle
        {bundle}.ts   # everything that bundle owns -- its requested root
                      # models and anything it needs internally, together

    A file only ever references defs from files that are fully evaluated before
    it runs, so cross-file imports are always safe; within a single file
    `_topo_order` is what keeps references from pointing forward.
    """
    index = build_schema_index(bundles)
    patterns = PatternRegistry()
    ctx = _Context(
        index=index,
        shared=index.shared_defs(),
        results={n: render_zod_schema(n, e, patterns) for n, e in index.defs.items()},
        patterns=patterns,
        output_dir=Path(output_dir),
    )
    written: list[Path] = []

    unresolved = [u for r in ctx.results.values() for u in r.unknowns]
    for entry in unresolved:
        logger.warning("code_gen: no Zod rule for %s -- emitted z.unknown()", entry)
    if unresolved:
        logger.warning(
            "code_gen: %s field(s) accept anything in the browser; "
            "they are marked UNRESOLVED in the generated files",
            len(unresolved),
        )

    all_patterns = {p for r in ctx.results.values() for p in r.pattern_names}
    if ctx.shared or all_patterns:
        written.append(_write_def_file(ctx, "shared", sorted(ctx.shared), all_patterns))

    for bundle in bundles:
        owned = sorted(n for n in index.defs if index.owning_bundle(n) == bundle.name)
        written.append(_write_def_file(ctx, bundle.name, owned, set()))

    return written
