"""Written by Claude (Anthropic).

Renders the `pytypes` type IR as real Zod schemas and writes them to
disk. This is the only code-generation module -- one generator, one file.

Output layout (all flat under `output_dir`, no subfolders):

    shared.ts        # patterns + schemas for defs used by >1 bundle
    form-schemas.ts   # Angular Signal Forms adapters + one
                       # ...FormSchema export per requested entity
    {bundle}.ts        # everything that bundle owns -- its requested root
                        # models and anything it needs internally, together

Every field, including a reference to another model, matches its source
pydantic model strictly -- no relaxations like accepting a bare string in
place of a nested object.

Worth knowing before reading the rest: every file only ever references
defs from files that are fully evaluated before it runs (imports), except
within a single file, where JS `const` bindings are NOT hoisted: a schema
referencing another schema declared later in the *same* file throws
"Cannot access X before initialization" at runtime. `_topo_order()` exists
specifically to prevent that.
"""
# mypy: ignore-errors
from __future__ import annotations

import json
import posixpath
import re
from dataclasses import dataclass, field
from pathlib import Path

from .bundle import Bundle
from .patterns import PatternRegistry
from .pytypes import EnumRef, FieldSpec, ListNode, LiteralNode, Node, ObjectRef, ScalarNode, UnionNode
from .schema_collect import DefEntry, EnumDef, ModelDef, SchemaIndex, build_schema_index

SUFFIX = ".ts"
ESLINT_DISABLE = "/* eslint-disable @typescript-eslint/naming-convention */"
HEADER = "// AUTO-GENERATED by mex_form_codegen -- do not edit by hand."


def kebab(name: str) -> str:
    """PascalCase/camelCase -> kebab-case (Angular's file-naming default):
    `ExtractedActivity` -> `extracted-activity`."""
    return re.sub(r"(?<!^)(?=[A-Z])", "-", name).lower()


def jsdoc(text: str) -> str:
    """A `/** ... */` block comment -- every exported declaration gets one
    of these, never a `//` line comment."""
    return f"/**\n * {text}\n */\n"


def import_specifier(from_parts: tuple[str, ...], to_parts: tuple[str, ...]) -> str:
    """Relative TS import specifier (no extension, kebab-cased) between
    two files, each given as path segments (dirs..., filename) relative
    to the output root. Always starts with `./` or `../` -- a specifier
    without one of those is a bare/node_modules import, not a relative
    file path."""
    from_parts, to_parts = tuple(kebab(p) for p in from_parts), tuple(kebab(p) for p in to_parts)
    from_dir = posixpath.join(*from_parts[:-1]) if len(from_parts) > 1 else "."
    to_dir = posixpath.join(*to_parts[:-1]) if len(to_parts) > 1 else "."
    rel = posixpath.relpath(to_dir, start=from_dir)
    path = to_parts[-1] if rel == "." else f"{rel}/{to_parts[-1]}"
    return path if path.startswith(("./", "../")) else f"./{path}"


def _write(output_dir: Path, file_parts: tuple[str, ...], body: str) -> Path:
    text = f"{ESLINT_DISABLE}\n{HEADER}\n\n{body}"
    path = output_dir / Path(*(kebab(p) for p in file_parts)).with_suffix(SUFFIX)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    return path


def _topo_order(names: list[str], deps: dict[str, set[str]]) -> list[str]:
    """Order `names` so every name comes after whichever *other* names in
    `names` it depends on -- otherwise alphabetical, for a deterministic
    diff between runs. Prevents "used before declared" for same-file
    `const` references (see module docstring)."""
    names_set, seen, order = set(names), set(), []

    def visit(n: str, stack: set[str]) -> None:
        if n in seen or n in stack:  # already placed, or a cycle -- don't hang
            return
        stack = stack | {n}
        for dep in sorted(deps.get(n, ()) & names_set):
            visit(dep, stack)
        seen.add(n)
        order.append(n)

    for n in sorted(names):
        visit(n, set())
    return order


# ---------------------------------------------------------------------------
# pytypes.Node -> Zod expression
# ---------------------------------------------------------------------------


@dataclass
class ZodResult:
    """One def's generated Zod code, plus what it needs imported: other
    defs' schema constants (`def_refs`) and shared pattern constants
    (`pattern_names`)."""

    code: str = ""
    def_refs: set[str] = field(default_factory=set)
    pattern_names: set[str] = field(default_factory=set)


def _scalar_zod(node: ScalarNode, patterns: PatternRegistry, field_name: str | None, r: ZodResult) -> str:
    # Base type first, then chain on whatever constraints this scalar has.
    base = "z.boolean()" if node.py_type is bool else "z.number()" if node.py_type in (int, float) else "z.string()"
    if node.py_type is str and node.pattern:
        name = patterns.name_for(node.pattern, node.leaf_cls.__name__, field_name)
        r.pattern_names.add(name)
        base += f".regex(new RegExp({name}))"
    elif node.format == "email":
        base += ".email()"
    if node.py_type is str:
        if node.min_length is not None:
            base += f".min({node.min_length})"
        if node.max_length is not None:
            base += f".max({node.max_length})"
    if node.py_type in (int, float):
        if node.minimum is not None:
            base += f".min({node.minimum})"
        if node.maximum is not None:
            base += f".max({node.maximum})"
    return base


def zod_for_node(node: Node, patterns: PatternRegistry, r: ZodResult, field_name: str | None = None) -> str:
    """The Zod expression for one field's resolved node (recursive). A
    reference to another model is a union of a bare string (an id/
    reference) and the full embedded object -- the referenced model's own
    schema never carries that union itself, only field sites that point
    at it do."""
    if isinstance(node, ObjectRef):
        r.def_refs.add(node.cls.__name__)
        return f"{node.cls.__name__}Schema"
    if isinstance(node, EnumRef):
        r.def_refs.add(node.cls.__name__)
        return f"{node.cls.__name__}Schema"
    if isinstance(node, LiteralNode):
        return " ".join(f'z.literal("{v}")' if isinstance(v, str) else f"z.literal({v!r})" for v in node.values)
    if isinstance(node, ListNode):
        arr = f"z.array({zod_for_node(node.item, patterns, r, field_name)})"
        if node.min_length is not None:
            arr += f".min({node.min_length})"
        if node.max_length is not None:
            arr += f".max({node.max_length})"
        return arr
    if isinstance(node, UnionNode):
        scalars = [m for m in node.members if isinstance(m, ScalarNode)]
        if len(scalars) == len(node.members) and scalars and all(m.pattern for m in scalars):
            # Union of patterned scalars (e.g. YearMonthDay | YearMonth |
            # Year) -> try each regex in turn.
            parts = list(dict.fromkeys(_scalar_zod(m, patterns, field_name, r) for m in scalars))
            return parts[0] if len(parts) == 1 else f"z.union([{', '.join(parts)}])"
        return f"z.union([{', '.join(zod_for_node(m, patterns, r, field_name) for m in node.members)}])"
    if isinstance(node, ScalarNode):
        return _scalar_zod(node, patterns, field_name, r)
    return "z.unknown()"


def render_zod_schema(name: str, entry: DefEntry, patterns: PatternRegistry) -> ZodResult:
    """The `export const {name}Schema = ...` + `export type {name} =
    z.infer<...>` block for one def, each with its own `/** */` doc
    comment. Always a plain object/enum schema -- see `zod_for_node` for
    where the string-or-object union actually lives."""
    r = ZodResult()

    if isinstance(entry, EnumDef):
        values = ", ".join(f'"{m.value}"' for m in entry.cls)
        r.code = (
            f"{jsdoc(f'Zod schema for the {name} enum.')}"
            f"export const {name}Schema = z.enum([{values}]);\n\n"
            f"{jsdoc(f'TypeScript type inferred from {name}Schema.')}"
            f"export type {name} = z.infer<typeof {name}Schema>;\n\n"
        )
        return r

    fields: list[str] = []
    for f in entry.fields:
        z = zod_for_node(f.node, patterns, r, f.py_name)
        is_fixed_literal = isinstance(f.node, LiteralNode) and len(f.node.values) == 1
        if not is_fixed_literal:
            if f.nullable and not f.required:
                # pydantic dumps an unset Optional[X] field as explicit
                # JSON null, not a missing key -- .optional() alone only
                # covers "key absent", so a nullable-and-not-required
                # field needs BOTH allowed.
                z += ".nullish()"
            elif f.nullable:
                z += ".nullable()"
            elif not f.required:
                z += ".optional()"
        fields.append(f"  {f.alias}: {z},")

    body = "z.object({\n" + "\n".join(fields) + "\n})"
    doc = f"Zod schema for {name}."
    if entry.extends:
        r.def_refs.add(entry.extends)
        body = f"{entry.extends}Schema.extend({{\n" + "\n".join(fields) + "\n})"
        doc = f"Zod schema for {name} (extends {entry.extends})."

    r.code = (
        f"{jsdoc(doc)}"
        f"export const {name}Schema = {body};\n\n"
        f"{jsdoc(f'TypeScript type inferred from {name}Schema.')}"
        f"export type {name} = z.infer<typeof {name}Schema>;\n\n"
    )
    return r


# ---------------------------------------------------------------------------
# File assembly
# ---------------------------------------------------------------------------


def _loc(name: str, index: SchemaIndex, shared: set[str]) -> tuple[str, ...]:
    """The file (as path segments) that declares `name`'s schema: the
    shared file if used by >1 bundle, otherwise its one owning bundle's
    single file."""
    return ("shared",) if name in shared else (index.owning_bundle(name),)


def _write_def_file(
    index: SchemaIndex,
    shared: set[str],
    results: dict[str, ZodResult],
    file_parts: tuple[str, ...],
    def_names: list[str],
    output_dir: Path,
    patterns: PatternRegistry,
    declare_patterns: set[str],
) -> Path:
    """Writes one file containing zero or more defs (topologically
    ordered so same-file references never point forward) plus whatever
    imports they need."""
    def_names = _topo_order(def_names, {n: results[n].def_refs for n in def_names})
    local = set(def_names)
    refs: set[str] = set()
    pattern_names: set[str] = set()
    for n in def_names:
        refs |= results[n].def_refs
        pattern_names |= results[n].pattern_names

    by_specifier: dict[str, set[str]] = {}
    if pattern_names and not declare_patterns:
        by_specifier.setdefault(import_specifier(file_parts, ("shared",)), set()).update(pattern_names)
    for ref in refs - local:
        by_specifier.setdefault(import_specifier(file_parts, _loc(ref, index, shared)), set()).add(f"{ref}Schema")

    imports = ['import { z } from "zod";']
    for spec, names in sorted(by_specifier.items()):
        imports.append(f'import {{ {", ".join(sorted(names))} }} from "{spec}";')

    body_parts = []
    if declare_patterns:
        lines = [
            f"{jsdoc('Regex pattern (deduplicated across every bundle).')}export const {n} = {json.dumps(p)};\n"
            for p, n in patterns.all_patterns().items()
            if n in declare_patterns
        ]
        body_parts.append("\n".join(lines) + "\n")
    body_parts += [results[n].code for n in def_names]

    return _write(output_dir, file_parts, "\n".join(imports) + "\n\n" + "".join(body_parts))


_UTILS_CODE = f"""\
{jsdoc("Runs `zodSchema` against the current field value and reports the first Zod issues as Angular Signal Forms validation errors.")}\
export function validateWithZod<T>(path: SchemaPath<T>, zodSchema: ZodType<T>): void {{
  validate(path, (ctx) => {{
    const result = zodSchema.safeParse(ctx.value());
    if (result.success) return null;
    return result.error.issues.map((issue) => ({{ kind: issue.code, message: issue.message }}));
  }});
}}

{jsdoc("Turns any Zod schema into an Angular Signal Forms schema function, ready to pass to schema<T>(...).")}\
export function zodFormSchema<T>(zodSchema: ZodType<T>) {{
  return (path: SchemaPathTree<T>) => validateWithZod(path as unknown as SchemaPath<T>, zodSchema);
}}
"""

def generate_zod_schemas(bundles: list[Bundle], output_dir: str | Path) -> list[Path]:
    """Generate everything: `shared.ts` (defs used by >1 bundle),
    `form-schemas.ts`, and one `{bundle}.ts` per bundle holding every def
    that bundle owns (its requested root models and anything it needs
    internally, together). Returns the written paths.
    """
    output_dir = Path(output_dir)
    index = build_schema_index(bundles)
    shared = index.shared_defs()
    patterns = PatternRegistry()
    results = {n: render_zod_schema(n, e, patterns) for n, e in index.defs.items()}
    written: list[Path] = []

    all_patterns = {p for r in results.values() for p in r.pattern_names}
    if shared or all_patterns:
        written.append(_write_def_file(index, shared, results, ("shared",), sorted(shared), output_dir, patterns, all_patterns))

    for bundle in bundles:
        owned = sorted(n for n in index.defs if index.owning_bundle(n) == bundle.name)
        written.append(_write_def_file(index, shared, results, (bundle.name,), owned, output_dir, patterns, set()))

    return written
