/* eslint-disable @typescript-eslint/naming-convention */
/* eslint-disable typedoc/require-exported-doc-comment */
// AUTO-GENERATED by mex_form_codegen -- do not edit by hand.
import { z } from "zod";

import {
  doiPattern,
  identifierPattern,
  loincIdPattern,
  meshIdPattern,
  yearMonthDayPattern,
  yearMonthDayTimePattern,
  yearMonthPattern,
  yearPattern,
} from "./../shared";
import { LinkSchema, TextSchema, ThemeSchema } from "./../shared";
import {
  AccessRestrictionSchema,
  AnonymizationPseudonymizationSchema,
  DataProcessingStateSchema,
  FrequencySchema,
  HealthCategorySchema,
  LanguageSchema,
  LicenseSchema,
  PersonalDataSchema,
  ResourceCreationMethodSchema,
  ResourceTypeGeneralSchema,
} from "./support";

export const PreviewResourceSchema = z.union([
  z.string().regex(new RegExp(identifierPattern)),
  z.object({
    accessRestriction: z.array(AccessRestrictionSchema).optional(),
    accrualPeriodicity: z.array(FrequencySchema).optional(),
    created: z
      .array(
        z.union([
          z.string().regex(new RegExp(yearMonthDayTimePattern)),
          z.string().regex(new RegExp(yearMonthDayPattern)),
          z.string().regex(new RegExp(yearMonthPattern)),
          z.string().regex(new RegExp(yearPattern)),
        ]),
      )
      .optional(),
    doi: z.array(z.string().regex(new RegExp(doiPattern))).optional(),
    hasPersonalData: z.array(PersonalDataSchema).optional(),
    license: z.array(LicenseSchema).optional(),
    maxTypicalAge: z.array(z.number()).optional(),
    minTypicalAge: z.array(z.number()).optional(),
    modified: z
      .array(
        z.union([
          z.string().regex(new RegExp(yearMonthDayTimePattern)),
          z.string().regex(new RegExp(yearMonthDayPattern)),
          z.string().regex(new RegExp(yearMonthPattern)),
          z.string().regex(new RegExp(yearPattern)),
        ]),
      )
      .optional(),
    numberOfRecords: z.array(z.number()).optional(),
    numberOfUniqueIndividuals: z.array(z.number()).optional(),
    sizeOfDataBasis: z.array(z.string()).optional(),
    temporal: z
      .array(
        z.union([
          z.string().regex(new RegExp(yearMonthDayTimePattern)),
          z.string().regex(new RegExp(yearMonthDayPattern)),
          z.string().regex(new RegExp(yearMonthPattern)),
          z.string().regex(new RegExp(yearPattern)),
          z.string(),
        ]),
      )
      .optional(),
    wasGeneratedBy: z.array(z.string().regex(new RegExp(identifierPattern))).optional(),
    contact: z.array(z.string().regex(new RegExp(identifierPattern))).optional(),
    theme: z.array(ThemeSchema).optional(),
    title: z.array(TextSchema).optional(),
    unitInCharge: z.array(z.string().regex(new RegExp(identifierPattern))).optional(),
    accessPlatform: z.array(z.string().regex(new RegExp(identifierPattern))).optional(),
    alternativeTitle: z.array(TextSchema).optional(),
    analytics: z.array(z.string().regex(new RegExp(identifierPattern))).optional(),
    anonymizationPseudonymization: z.array(AnonymizationPseudonymizationSchema).optional(),
    conformsTo: z.array(z.string()).optional(),
    contributingUnit: z.array(z.string().regex(new RegExp(identifierPattern))).optional(),
    contributor: z.array(z.string().regex(new RegExp(identifierPattern))).optional(),
    creator: z.array(z.string().regex(new RegExp(identifierPattern))).optional(),
    description: z.array(TextSchema).optional(),
    distribution: z.array(z.string().regex(new RegExp(identifierPattern))).optional(),
    documentation: z.array(LinkSchema).optional(),
    end: z
      .array(
        z.union([
          z.string().regex(new RegExp(yearMonthDayTimePattern)),
          z.string().regex(new RegExp(yearMonthDayPattern)),
          z.string().regex(new RegExp(yearMonthPattern)),
          z.string().regex(new RegExp(yearPattern)),
        ]),
      )
      .optional(),
    externalPartner: z.array(z.string().regex(new RegExp(identifierPattern))).optional(),
    hasCodeValues: z.array(TextSchema).optional(),
    hasLegalBasis: z.array(TextSchema).optional(),
    hasPurpose: z.array(TextSchema).optional(),
    healthCategory: z.array(HealthCategorySchema).optional(),
    icd10code: z.array(z.string()).optional(),
    instrumentToolOrApparatus: z.array(TextSchema).optional(),
    isPartOf: z.array(z.string().regex(new RegExp(identifierPattern))).optional(),
    keyword: z.array(TextSchema).optional(),
    language: z.array(LanguageSchema).optional(),
    loincId: z.array(z.string().regex(new RegExp(loincIdPattern))).optional(),
    meshId: z.array(z.string().regex(new RegExp(meshIdPattern))).optional(),
    method: z.array(TextSchema).optional(),
    methodDescription: z.array(TextSchema).optional(),
    populationCoverage: z.array(TextSchema).optional(),
    provenance: z.array(TextSchema).optional(),
    publication: z.array(z.string().regex(new RegExp(identifierPattern))).optional(),
    publisher: z.array(z.string().regex(new RegExp(identifierPattern))).optional(),
    qualityInformation: z.array(TextSchema).optional(),
    relatedResource: z.array(z.string().regex(new RegExp(identifierPattern))).optional(),
    resourceCreationMethod: z.array(ResourceCreationMethodSchema).optional(),
    resourceTypeGeneral: z.array(ResourceTypeGeneralSchema).optional(),
    resourceTypeSpecific: z.array(TextSchema).optional(),
    rights: z.array(TextSchema).optional(),
    sample: z.array(z.string().regex(new RegExp(identifierPattern))).optional(),
    source: z.array(z.string().regex(new RegExp(identifierPattern))).optional(),
    spatial: z.array(TextSchema).optional(),
    start: z
      .array(
        z.union([
          z.string().regex(new RegExp(yearMonthDayTimePattern)),
          z.string().regex(new RegExp(yearMonthDayPattern)),
          z.string().regex(new RegExp(yearMonthPattern)),
          z.string().regex(new RegExp(yearPattern)),
        ]),
      )
      .optional(),
    stateOfDataProcessing: z.array(DataProcessingStateSchema).optional(),
    $type: z.literal("PreviewResource"),
    identifier: z.string().regex(new RegExp(identifierPattern)),
    supersededBy: z.string().regex(new RegExp(identifierPattern)).optional(),
  }),
]);
export type PreviewResource = z.infer<typeof PreviewResourceSchema>;
