/* eslint-disable @typescript-eslint/naming-convention */
/* eslint-disable typedoc/require-exported-doc-comment */
// AUTO-GENERATED by mex_form_codegen -- do not edit by hand.
import { z } from "zod";

import {
  doiPattern,
  identifierPattern,
  loincIdPattern,
  meshIdPattern,
  yearMonthDayPattern,
  yearMonthDayTimePattern,
  yearMonthPattern,
  yearPattern,
} from "./../shared";
import { LinkSchema, TextSchema, ThemeSchema } from "./../shared";

export const AccessRestrictionSchema = z.enum([
  "https://mex.rki.de/item/access-restriction-1",
  "https://mex.rki.de/item/access-restriction-2",
]);
export type AccessRestriction = z.infer<typeof AccessRestrictionSchema>;

export const AnonymizationPseudonymizationSchema = z.enum([
  "https://mex.rki.de/item/anonymization-pseudonymization-1",
  "https://mex.rki.de/item/anonymization-pseudonymization-2",
]);
export type AnonymizationPseudonymization = z.infer<typeof AnonymizationPseudonymizationSchema>;

export const DataProcessingStateSchema = z.enum([
  "https://mex.rki.de/item/data-processing-state-1",
  "https://mex.rki.de/item/data-processing-state-2",
  "https://mex.rki.de/item/data-processing-state-3",
  "https://mex.rki.de/item/data-processing-state-4",
  "https://mex.rki.de/item/data-processing-state-5",
]);
export type DataProcessingState = z.infer<typeof DataProcessingStateSchema>;

export const FrequencySchema = z.enum([
  "https://mex.rki.de/item/frequency-1",
  "https://mex.rki.de/item/frequency-2",
  "https://mex.rki.de/item/frequency-3",
  "https://mex.rki.de/item/frequency-4",
  "https://mex.rki.de/item/frequency-5",
  "https://mex.rki.de/item/frequency-6",
  "https://mex.rki.de/item/frequency-7",
  "https://mex.rki.de/item/frequency-8",
  "https://mex.rki.de/item/frequency-9",
  "https://mex.rki.de/item/frequency-10",
  "https://mex.rki.de/item/frequency-11",
  "https://mex.rki.de/item/frequency-12",
  "https://mex.rki.de/item/frequency-13",
  "https://mex.rki.de/item/frequency-14",
  "https://mex.rki.de/item/frequency-15",
  "https://mex.rki.de/item/frequency-16",
  "https://mex.rki.de/item/frequency-17",
]);
export type Frequency = z.infer<typeof FrequencySchema>;

export const HealthCategorySchema = z.enum([
  "https://mex.rki.de/item/health-category-1",
  "https://mex.rki.de/item/health-category-2",
  "https://mex.rki.de/item/health-category-3",
  "https://mex.rki.de/item/health-category-4",
  "https://mex.rki.de/item/health-category-5",
  "https://mex.rki.de/item/health-category-6",
  "https://mex.rki.de/item/health-category-7",
  "https://mex.rki.de/item/health-category-8",
  "https://mex.rki.de/item/health-category-9",
  "https://mex.rki.de/item/health-category-10",
  "https://mex.rki.de/item/health-category-11",
  "https://mex.rki.de/item/health-category-12",
  "https://mex.rki.de/item/health-category-13",
  "https://mex.rki.de/item/health-category-14",
  "https://mex.rki.de/item/health-category-15",
  "https://mex.rki.de/item/health-category-16",
  "https://mex.rki.de/item/health-category-17",
]);
export type HealthCategory = z.infer<typeof HealthCategorySchema>;

export const LanguageSchema = z.enum([
  "https://mex.rki.de/item/language-1",
  "https://mex.rki.de/item/language-2",
  "https://mex.rki.de/item/language-3",
  "https://mex.rki.de/item/language-4",
  "https://mex.rki.de/item/language-5",
]);
export type Language = z.infer<typeof LanguageSchema>;

export const LicenseSchema = z.enum(["https://mex.rki.de/item/license-1"]);
export type License = z.infer<typeof LicenseSchema>;

export const PersonalDataSchema = z.enum([
  "https://mex.rki.de/item/personal-data-1",
  "https://mex.rki.de/item/personal-data-2",
]);
export type PersonalData = z.infer<typeof PersonalDataSchema>;

export const ResourceCreationMethodSchema = z.enum([
  "https://mex.rki.de/item/resource-creation-method-1",
  "https://mex.rki.de/item/resource-creation-method-2",
  "https://mex.rki.de/item/resource-creation-method-3",
  "https://mex.rki.de/item/resource-creation-method-4",
  "https://mex.rki.de/item/resource-creation-method-5",
  "https://mex.rki.de/item/resource-creation-method-6",
  "https://mex.rki.de/item/resource-creation-method-7",
]);
export type ResourceCreationMethod = z.infer<typeof ResourceCreationMethodSchema>;

export const ResourceTypeGeneralSchema = z.enum([
  "https://mex.rki.de/item/resource-type-general-2",
  "https://mex.rki.de/item/resource-type-general-13",
  "https://mex.rki.de/item/resource-type-general-14",
  "https://mex.rki.de/item/resource-type-general-15",
  "https://mex.rki.de/item/resource-type-general-16",
  "https://mex.rki.de/item/resource-type-general-17",
  "https://mex.rki.de/item/resource-type-general-18",
]);
export type ResourceTypeGeneral = z.infer<typeof ResourceTypeGeneralSchema>;

export const BaseResourceSchema = z.object({
  accessRestriction: AccessRestrictionSchema,
  accrualPeriodicity: FrequencySchema.optional(),
  created: z
    .union([
      z.string().regex(new RegExp(yearMonthDayTimePattern)),
      z.string().regex(new RegExp(yearMonthDayPattern)),
      z.string().regex(new RegExp(yearMonthPattern)),
      z.string().regex(new RegExp(yearPattern)),
    ])
    .optional(),
  doi: z.string().regex(new RegExp(doiPattern)).optional(),
  hasPersonalData: PersonalDataSchema.optional(),
  license: LicenseSchema.optional(),
  maxTypicalAge: z.number().optional(),
  minTypicalAge: z.number().optional(),
  modified: z
    .union([
      z.string().regex(new RegExp(yearMonthDayTimePattern)),
      z.string().regex(new RegExp(yearMonthDayPattern)),
      z.string().regex(new RegExp(yearMonthPattern)),
      z.string().regex(new RegExp(yearPattern)),
    ])
    .optional(),
  numberOfRecords: z.number().optional(),
  numberOfUniqueIndividuals: z.number().optional(),
  sizeOfDataBasis: z.string().optional(),
  temporal: z
    .union([
      z.string().regex(new RegExp(yearMonthDayTimePattern)),
      z.string().regex(new RegExp(yearMonthDayPattern)),
      z.string().regex(new RegExp(yearMonthPattern)),
      z.string().regex(new RegExp(yearPattern)),
      z.string(),
    ])
    .optional(),
  wasGeneratedBy: z.string().regex(new RegExp(identifierPattern)).optional(),
  contact: z.array(z.string().regex(new RegExp(identifierPattern))).min(1),
  theme: z.array(ThemeSchema).min(1),
  title: z.array(TextSchema).min(1),
  unitInCharge: z.array(z.string().regex(new RegExp(identifierPattern))).min(1),
  accessPlatform: z.array(z.string().regex(new RegExp(identifierPattern))).optional(),
  alternativeTitle: z.array(TextSchema).optional(),
  analytics: z.array(z.string().regex(new RegExp(identifierPattern))).optional(),
  anonymizationPseudonymization: z.array(AnonymizationPseudonymizationSchema).optional(),
  conformsTo: z.array(z.string()).optional(),
  contributingUnit: z.array(z.string().regex(new RegExp(identifierPattern))).optional(),
  contributor: z.array(z.string().regex(new RegExp(identifierPattern))).optional(),
  creator: z.array(z.string().regex(new RegExp(identifierPattern))).optional(),
  description: z.array(TextSchema).optional(),
  distribution: z.array(z.string().regex(new RegExp(identifierPattern))).optional(),
  documentation: z.array(LinkSchema).optional(),
  end: z
    .array(
      z.union([
        z.string().regex(new RegExp(yearMonthDayTimePattern)),
        z.string().regex(new RegExp(yearMonthDayPattern)),
        z.string().regex(new RegExp(yearMonthPattern)),
        z.string().regex(new RegExp(yearPattern)),
      ]),
    )
    .optional(),
  externalPartner: z.array(z.string().regex(new RegExp(identifierPattern))).optional(),
  hasCodeValues: z.array(TextSchema).optional(),
  hasLegalBasis: z.array(TextSchema).optional(),
  hasPurpose: z.array(TextSchema).optional(),
  healthCategory: z.array(HealthCategorySchema).optional(),
  icd10code: z.array(z.string()).optional(),
  instrumentToolOrApparatus: z.array(TextSchema).optional(),
  isPartOf: z.array(z.string().regex(new RegExp(identifierPattern))).optional(),
  keyword: z.array(TextSchema).optional(),
  language: z.array(LanguageSchema).optional(),
  loincId: z.array(z.string().regex(new RegExp(loincIdPattern))).optional(),
  meshId: z.array(z.string().regex(new RegExp(meshIdPattern))).optional(),
  method: z.array(TextSchema).optional(),
  methodDescription: z.array(TextSchema).optional(),
  populationCoverage: z.array(TextSchema).optional(),
  provenance: z.array(TextSchema).optional(),
  publication: z.array(z.string().regex(new RegExp(identifierPattern))).optional(),
  publisher: z.array(z.string().regex(new RegExp(identifierPattern))).optional(),
  qualityInformation: z.array(TextSchema).optional(),
  relatedResource: z.array(z.string().regex(new RegExp(identifierPattern))).optional(),
  resourceCreationMethod: z.array(ResourceCreationMethodSchema).optional(),
  resourceTypeGeneral: z.array(ResourceTypeGeneralSchema).optional(),
  resourceTypeSpecific: z.array(TextSchema).optional(),
  rights: z.array(TextSchema).optional(),
  sample: z.array(z.string().regex(new RegExp(identifierPattern))).optional(),
  source: z.array(z.string().regex(new RegExp(identifierPattern))).optional(),
  spatial: z.array(TextSchema).optional(),
  start: z
    .array(
      z.union([
        z.string().regex(new RegExp(yearMonthDayTimePattern)),
        z.string().regex(new RegExp(yearMonthDayPattern)),
        z.string().regex(new RegExp(yearMonthPattern)),
        z.string().regex(new RegExp(yearPattern)),
      ]),
    )
    .optional(),
  stateOfDataProcessing: z.array(DataProcessingStateSchema).optional(),
});
export type BaseResource = z.infer<typeof BaseResourceSchema>;
