/* eslint-disable @typescript-eslint/no-inferrable-types */
/* eslint-disable @typescript-eslint/naming-convention */
/* eslint-disable typedoc/require-exported-doc-comment */
// AUTO-GENERATED by mex_form_codegen -- do not edit by hand.
import { z } from "zod";

// -- Regex patterns, deduplicated across every bundle --
export const identifierPattern: string = "^[a-zA-Z0-9]{14,22}$";
export const yearMonthDayTimePattern: string =
  "^[0-9]{4}-(?:0[1-9]|1[0-2])-(?:0[1-9]|[12][0-9]|3[01])T(?:[0-1][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]Z$";
export const yearMonthDayPattern: string =
  "^[0-9]{4}-(?:0[1-9]|1[0-2])-(?:0[1-9]|[12][0-9]|3[01])$";
export const yearMonthPattern: string = "^[0-9]{4}-(?:0[1-9]|1[0-2])$";
export const yearPattern: string = "^[0-9]{4}$";
export const doiPattern: string =
  "^https?://(?:dx\\.)?doi\\.org/[0-9]{2}\\.[0-9]{4,9}[-_.;()/:A-Za-z0-9]{0,256}$";
export const loincIdPattern: string = "^https://loinc\\.org/[-A-Za-z0-9]{2,64}$";
export const meshIdPattern: string = "^http://id\\.nlm\\.nih\\.gov/mesh/[A-Z0-9]{2,64}$";
export const urlPattern: string =
  "^(?:(?:[^:/?#]+):)?(?://(?:[^/?#]*))?(?:[^?#]*)(?:\\?(?:[^#]*))?(?:#(?:.*))?$";
export const identifierInPrimarySourcePattern: string = "^[^\\n\\r]+$";
export const emailPattern: string = "^[^@ \\t\\r\\n]+@[^@ \\t\\r\\n]+\\.[^@ \\t\\r\\n]+$";
export const isniIdPattern: string = "^https://isni\\.org/isni/[X0-9]{16}$";
export const orcidIdPattern: string = "^https://orcid\\.org/[-X0-9]{9,21}$";
export const geprisIdPattern: string = "^https://gepris\\.dfg\\.de/gepris/institution/[0-9]{1,64}$";
export const gndIdPattern: string = "^https://d-nb\\.info/gnd/[-X0-9]{3,10}$";
export const rorIdPattern: string = "^https://ror\\.org/[a-z0-9]{9}$";
export const viafIdPattern: string = "^https://viaf\\.org/viaf/[0-9]{2,22}$";
export const wikidataIdPattern: string = "^http://www\\.wikidata\\.org/entity/[PQ0-9]{2,64}$";

export const LinkLanguageSchema = z.enum(["de", "en", "fr", "es", "ru"]);
export type LinkLanguage = z.infer<typeof LinkLanguageSchema>;

export const LinkSchema = z.union([
  z.string().regex(new RegExp(urlPattern)).min(1),
  z.object({
    language: LinkLanguageSchema.optional(),
    title: z.string().optional(),
    url: z.string().regex(new RegExp(urlPattern)).min(1),
  }),
]);
export type Link = z.infer<typeof LinkSchema>;

export const PublishingTargetSchema = z.enum(["invenio", "datenkompass"]);
export type PublishingTarget = z.infer<typeof PublishingTargetSchema>;

export const TextLanguageSchema = z.enum(["de", "en", "fr", "es", "ru"]);
export type TextLanguage = z.infer<typeof TextLanguageSchema>;

export const TextSchema = z.union([
  z.string().min(1),
  z.object({
    value: z.string().min(1),
    language: TextLanguageSchema.optional(),
  }),
]);
export type Text = z.infer<typeof TextSchema>;

export const ThemeSchema = z.enum([
  "https://mex.rki.de/item/theme-1",
  "https://mex.rki.de/item/theme-11",
  "https://mex.rki.de/item/theme-20",
  "https://mex.rki.de/item/theme-21",
  "https://mex.rki.de/item/theme-22",
  "https://mex.rki.de/item/theme-23",
  "https://mex.rki.de/item/theme-24",
  "https://mex.rki.de/item/theme-25",
  "https://mex.rki.de/item/theme-36",
  "https://mex.rki.de/item/theme-37",
]);
export type Theme = z.infer<typeof ThemeSchema>;
