// AUTO-GENERATED by mex_form_codegen -- do not edit by hand.
import type { Link, PublishingTarget, Text, Theme } from "./shared";

/** Set of rules to create or update an activity item. */
export interface ActivityRuleSetRequest {
  additive?: AdditiveActivity;
  subtractive?: SubtractiveActivity;
  preventive?: PreventiveActivity;
  workflow?: WorkflowActivity;
  $type: "ActivityRuleSetRequest";
}

/** Set of rules to retrieve an activity item. */
export interface ActivityRuleSetResponse {
  additive?: AdditiveActivity;
  subtractive?: SubtractiveActivity;
  preventive?: PreventiveActivity;
  workflow?: WorkflowActivity;
  $type: "ActivityRuleSetResponse";
  stableTargetId: string;
}

/** Rule to add values to merged activity items. */
export interface AdditiveActivity {
  /** An agent serving as a contact for the activity. */
  contact?: string[];
  /** A unit, that is responsible for the activity. */
  responsibleUnit?: string[];
  /** The official title of the activity. */
  title?: Text[];
  /** A short text describing the activity. */
  abstract?: Text[];
  /** The type of the activity. */
  activityType?: ActivityType[];
  /** Another name for the activity. */
  alternativeTitle?: Text[];
  /** A link to a document, that contains the documentation of the activity. */
  documentation?: Link[];
  /** (Planned) end of the activity. */
  end?: string[];
  /** An external institution or person, that is associated with the activity. */
  externalAssociate?: string[];
  /** An agent, that has either funded or commissioned the activity. */
  funderOrCommissioner?: string[];
  /** The program in which the activity is funded, e.g. Horizon2020. */
  fundingProgram?: string[];
  /** A person involved in the activity. */
  involvedPerson?: string[];
  /** An organizational unit that is involved in the activity. */
  involvedUnit?: string[];
  /** Another activity, this activity is part of. */
  isPartOfActivity?: string[];
  /** A publication related to the activity. */
  publication?: string[];
  /** A related Activity. */
  relatedActivity?: string[];
  /** A short name for, or an abbreviated title of, the activity. */
  shortName?: Text[];
  /** The start of the activity. */
  start?: string[];
  /** Another activity, that ended with the start of the described activity. A follow-up activity. */
  succeeds?: string[];
  /** The main theme or subject of the activity. */
  theme?: Theme[];
  /** A web presentation of the activity, e.g. on the RKI homepage. */
  website?: Link[];
  $type: "AdditiveActivity";
  supersededBy?: string;
}

/** An automatically extracted metadata set describing an activity. */
export interface ExtractedActivity extends BaseActivity {
  /** A primary source for a topic refers to something produced by some agent with direct experience and knowledge about the topic, at the time of the topic's study, without benefit from hindsight. Because of the directness of primary sources, they 'speak for themselves' in ways that cannot be captured through the filter of secondary sources. As such, it is important for secondary sources to reference those primary sources from which they were derived, so that their reliability can be investigated. A primary source relation is a particular case of derivation of secondary materials from their primary sources. It is recognized that the determination of primary sources can be up to interpretation, and should be done according to conventions accepted within the application's domain ([PROV-O, 2013-04-30 ](http://www.w3.org/TR/2013/REC-prov-o-20130430/)). */
  hadPrimarySource: string;
  /** The identifier of the item used in the primary source. */
  identifierInPrimarySource: string;
  $type: "ExtractedActivity";
}

/** The result of merging all extracted items and rules for an activity. */
export interface MergedActivity extends BaseActivity {
  $type: "MergedActivity";
  identifier: string;
  supersededBy?: string;
}

/** Rule to prevent primary sources for fields of merged activity items. */
export interface PreventiveActivity {
  $type: "PreventiveActivity";
  abstract?: string[];
  activityType?: string[];
  alternativeTitle?: string[];
  contact?: string[];
  documentation?: string[];
  end?: string[];
  externalAssociate?: string[];
  funderOrCommissioner?: string[];
  fundingProgram?: string[];
  involvedPerson?: string[];
  involvedUnit?: string[];
  isPartOfActivity?: string[];
  publication?: string[];
  responsibleUnit?: string[];
  relatedActivity?: string[];
  shortName?: string[];
  start?: string[];
  succeeds?: string[];
  theme?: string[];
  title?: string[];
  website?: string[];
}

/** Preview for merging all extracted items and rules for an activity. */
export interface PreviewActivity {
  /** An agent serving as a contact for the activity. */
  contact?: string[];
  /** A unit, that is responsible for the activity. */
  responsibleUnit?: string[];
  /** The official title of the activity. */
  title?: Text[];
  /** A short text describing the activity. */
  abstract?: Text[];
  /** The type of the activity. */
  activityType?: ActivityType[];
  /** Another name for the activity. */
  alternativeTitle?: Text[];
  /** A link to a document, that contains the documentation of the activity. */
  documentation?: Link[];
  /** (Planned) end of the activity. */
  end?: string[];
  /** An external institution or person, that is associated with the activity. */
  externalAssociate?: string[];
  /** An agent, that has either funded or commissioned the activity. */
  funderOrCommissioner?: string[];
  /** The program in which the activity is funded, e.g. Horizon2020. */
  fundingProgram?: string[];
  /** A person involved in the activity. */
  involvedPerson?: string[];
  /** An organizational unit that is involved in the activity. */
  involvedUnit?: string[];
  /** Another activity, this activity is part of. */
  isPartOfActivity?: string[];
  /** A publication related to the activity. */
  publication?: string[];
  /** A related Activity. */
  relatedActivity?: string[];
  /** A short name for, or an abbreviated title of, the activity. */
  shortName?: Text[];
  /** The start of the activity. */
  start?: string[];
  /** Another activity, that ended with the start of the described activity. A follow-up activity. */
  succeeds?: string[];
  /** The main theme or subject of the activity. */
  theme?: Theme[];
  /** A web presentation of the activity, e.g. on the RKI homepage. */
  website?: Link[];
  $type: "PreviewActivity";
  identifier: string;
  supersededBy?: string;
}

/** Rule to subtract values from merged activity items. */
export interface SubtractiveActivity {
  /** An agent serving as a contact for the activity. */
  contact?: string[];
  /** A unit, that is responsible for the activity. */
  responsibleUnit?: string[];
  /** The official title of the activity. */
  title?: Text[];
  /** A short text describing the activity. */
  abstract?: Text[];
  /** The type of the activity. */
  activityType?: ActivityType[];
  /** Another name for the activity. */
  alternativeTitle?: Text[];
  /** A link to a document, that contains the documentation of the activity. */
  documentation?: Link[];
  /** (Planned) end of the activity. */
  end?: string[];
  /** An external institution or person, that is associated with the activity. */
  externalAssociate?: string[];
  /** An agent, that has either funded or commissioned the activity. */
  funderOrCommissioner?: string[];
  /** The program in which the activity is funded, e.g. Horizon2020. */
  fundingProgram?: string[];
  /** A person involved in the activity. */
  involvedPerson?: string[];
  /** An organizational unit that is involved in the activity. */
  involvedUnit?: string[];
  /** Another activity, this activity is part of. */
  isPartOfActivity?: string[];
  /** A publication related to the activity. */
  publication?: string[];
  /** A related Activity. */
  relatedActivity?: string[];
  /** A short name for, or an abbreviated title of, the activity. */
  shortName?: Text[];
  /** The start of the activity. */
  start?: string[];
  /** Another activity, that ended with the start of the described activity. A follow-up activity. */
  succeeds?: string[];
  /** The main theme or subject of the activity. */
  theme?: Theme[];
  /** A web presentation of the activity, e.g. on the RKI homepage. */
  website?: Link[];
  $type: "SubtractiveActivity";
}

/** Rule to prevent publishing of merged activity items. */
export interface WorkflowActivity {
  /** Targets to which the merged item should NOT be published. */
  forbiddenPublishingTarget?: PublishingTarget[];
  $type: "WorkflowActivity";
}

/** The activity type. */
export type ActivityType =
  | "https://mex.rki.de/item/activity-type-1"
  | "https://mex.rki.de/item/activity-type-3"
  | "https://mex.rki.de/item/activity-type-6";

/** All fields for a valid activity except for provenance. */
export interface BaseActivity {
  /** An agent serving as a contact for the activity. */
  contact: string[];
  /** A unit, that is responsible for the activity. */
  responsibleUnit: string[];
  /** The official title of the activity. */
  title: Text[];
  /** A short text describing the activity. */
  abstract?: Text[];
  /** The type of the activity. */
  activityType?: ActivityType[];
  /** Another name for the activity. */
  alternativeTitle?: Text[];
  /** A link to a document, that contains the documentation of the activity. */
  documentation?: Link[];
  /** (Planned) end of the activity. */
  end?: string[];
  /** An external institution or person, that is associated with the activity. */
  externalAssociate?: string[];
  /** An agent, that has either funded or commissioned the activity. */
  funderOrCommissioner?: string[];
  /** The program in which the activity is funded, e.g. Horizon2020. */
  fundingProgram?: string[];
  /** A person involved in the activity. */
  involvedPerson?: string[];
  /** An organizational unit that is involved in the activity. */
  involvedUnit?: string[];
  /** Another activity, this activity is part of. */
  isPartOfActivity?: string[];
  /** A publication related to the activity. */
  publication?: string[];
  /** A related Activity. */
  relatedActivity?: string[];
  /** A short name for, or an abbreviated title of, the activity. */
  shortName?: Text[];
  /** The start of the activity. */
  start?: string[];
  /** Another activity, that ended with the start of the described activity. A follow-up activity. */
  succeeds?: string[];
  /** The main theme or subject of the activity. */
  theme?: Theme[];
  /** A web presentation of the activity, e.g. on the RKI homepage. */
  website?: Link[];
}
