// AUTO-GENERATED by mex_form_codegen -- do not edit by hand.
import type { PublishingTarget } from "./shared";

/** Rule to add values to merged contact point items. */
export interface AdditiveContactPoint {
  /** The email address associated to the contact point. */
  email?: string[];
  $type: "AdditiveContactPoint";
  supersededBy?: string;
}

/** Set of rules to create or update a contact point item. */
export interface ContactPointRuleSetRequest {
  additive?: AdditiveContactPoint;
  subtractive?: SubtractiveContactPoint;
  preventive?: PreventiveContactPoint;
  workflow?: WorkflowContactPoint;
  $type: "ContactPointRuleSetRequest";
}

/** Set of rules to retrieve a contact point item. */
export interface ContactPointRuleSetResponse {
  additive?: AdditiveContactPoint;
  subtractive?: SubtractiveContactPoint;
  preventive?: PreventiveContactPoint;
  workflow?: WorkflowContactPoint;
  $type: "ContactPointRuleSetResponse";
  stableTargetId: string;
}

/** An automatically extracted metadata set describing a contact point. */
export interface ExtractedContactPoint extends BaseContactPoint {
  /** A primary source for a topic refers to something produced by some agent with direct experience and knowledge about the topic, at the time of the topic's study, without benefit from hindsight. Because of the directness of primary sources, they 'speak for themselves' in ways that cannot be captured through the filter of secondary sources. As such, it is important for secondary sources to reference those primary sources from which they were derived, so that their reliability can be investigated. A primary source relation is a particular case of derivation of secondary materials from their primary sources. It is recognized that the determination of primary sources can be up to interpretation, and should be done according to conventions accepted within the application's domain ([PROV-O, 2013-04-30 ](http://www.w3.org/TR/2013/REC-prov-o-20130430/)). */
  hadPrimarySource: string;
  /** The identifier of the item used in the primary source. */
  identifierInPrimarySource: string;
  $type: "ExtractedContactPoint";
}

/** The result of merging all extracted items and rules for a contact point. */
export interface MergedContactPoint extends BaseContactPoint {
  $type: "MergedContactPoint";
  identifier: string;
  supersededBy?: string;
}

/** Rule to prevent primary sources for fields of merged contact point items. */
export interface PreventiveContactPoint {
  $type: "PreventiveContactPoint";
  email?: string[];
}

/** Preview for merging all extracted items and rules for a contact point. */
export interface PreviewContactPoint {
  /** The email address associated to the contact point. */
  email?: string[];
  $type: "PreviewContactPoint";
  identifier: string;
  supersededBy?: string;
}

/** Rule to subtract values from merged contact point items. */
export interface SubtractiveContactPoint {
  /** The email address associated to the contact point. */
  email?: string[];
  $type: "SubtractiveContactPoint";
}

/** Rule to prevent publishing of merged contact point items. */
export interface WorkflowContactPoint {
  /** Targets to which the merged item should NOT be published. */
  forbiddenPublishingTarget?: PublishingTarget[];
  $type: "WorkflowContactPoint";
}

/** All fields for a valid contact point except for provenance. */
export interface BaseContactPoint {
  /** The email address associated to the contact point. */
  email: string[];
}
