// AUTO-GENERATED by mex_form_codegen -- do not edit by hand.
import type { PublishingTarget, Text } from "./shared";

/** Rule to add values to merged organization items. */
export interface AdditiveOrganization {
  /** The official name of the organization. */
  officialName?: Text[];
  /** An alternative name for the organization */
  alternativeName?: Text[];
  /** Identifier from GEPRIS authority file. */
  geprisId?: string[];
  /** An identifier from the German authority file named Gemeinsame Normdatei (GND), curated by the German National Library (DNB). */
  gndId?: string[];
  /** The ISNI (International Standard Name Identifier) of the organization. */
  isniId?: string[];
  /** An identifier of the Research Organization Registry (ROR). */
  rorId?: string[];
  /** A short name or abbreviation of the organization. */
  shortName?: Text[];
  /** Identifier from VIAF (Virtual Authority File). */
  viafId?: string[];
  /** Identifier from Wikidata. */
  wikidataId?: string[];
  $type: "AdditiveOrganization";
  supersededBy?: string;
}

/** An automatically extracted metadata set describing an organization. */
export interface ExtractedOrganization extends BaseOrganization {
  /** A primary source for a topic refers to something produced by some agent with direct experience and knowledge about the topic, at the time of the topic's study, without benefit from hindsight. Because of the directness of primary sources, they 'speak for themselves' in ways that cannot be captured through the filter of secondary sources. As such, it is important for secondary sources to reference those primary sources from which they were derived, so that their reliability can be investigated. A primary source relation is a particular case of derivation of secondary materials from their primary sources. It is recognized that the determination of primary sources can be up to interpretation, and should be done according to conventions accepted within the application's domain ([PROV-O, 2013-04-30 ](http://www.w3.org/TR/2013/REC-prov-o-20130430/)). */
  hadPrimarySource: string;
  /** The identifier of the item used in the primary source. */
  identifierInPrimarySource: string;
  $type: "ExtractedOrganization";
}

/** The result of merging all extracted items and rules for an organization. */
export interface MergedOrganization extends BaseOrganization {
  $type: "MergedOrganization";
  identifier: string;
  supersededBy?: string;
}

/** Set of rules to create or update an organization item. */
export interface OrganizationRuleSetRequest {
  additive?: AdditiveOrganization;
  subtractive?: SubtractiveOrganization;
  preventive?: PreventiveOrganization;
  workflow?: WorkflowOrganization;
  $type: "OrganizationRuleSetRequest";
}

/** Set of rules to retrieve an organization item. */
export interface OrganizationRuleSetResponse {
  additive?: AdditiveOrganization;
  subtractive?: SubtractiveOrganization;
  preventive?: PreventiveOrganization;
  workflow?: WorkflowOrganization;
  $type: "OrganizationRuleSetResponse";
  stableTargetId: string;
}

/** Rule to prevent primary sources for fields of merged organization items. */
export interface PreventiveOrganization {
  $type: "PreventiveOrganization";
  alternativeName?: string[];
  geprisId?: string[];
  gndId?: string[];
  isniId?: string[];
  officialName?: string[];
  rorId?: string[];
  shortName?: string[];
  viafId?: string[];
  wikidataId?: string[];
}

/** Preview for merging all extracted items and rules for an organization. */
export interface PreviewOrganization {
  /** The official name of the organization. */
  officialName?: Text[];
  /** An alternative name for the organization */
  alternativeName?: Text[];
  /** Identifier from GEPRIS authority file. */
  geprisId?: string[];
  /** An identifier from the German authority file named Gemeinsame Normdatei (GND), curated by the German National Library (DNB). */
  gndId?: string[];
  /** The ISNI (International Standard Name Identifier) of the organization. */
  isniId?: string[];
  /** An identifier of the Research Organization Registry (ROR). */
  rorId?: string[];
  /** A short name or abbreviation of the organization. */
  shortName?: Text[];
  /** Identifier from VIAF (Virtual Authority File). */
  viafId?: string[];
  /** Identifier from Wikidata. */
  wikidataId?: string[];
  $type: "PreviewOrganization";
  identifier: string;
  supersededBy?: string;
}

/** Rule to subtract values from merged organization items. */
export interface SubtractiveOrganization {
  /** The official name of the organization. */
  officialName?: Text[];
  /** An alternative name for the organization */
  alternativeName?: Text[];
  /** Identifier from GEPRIS authority file. */
  geprisId?: string[];
  /** An identifier from the German authority file named Gemeinsame Normdatei (GND), curated by the German National Library (DNB). */
  gndId?: string[];
  /** The ISNI (International Standard Name Identifier) of the organization. */
  isniId?: string[];
  /** An identifier of the Research Organization Registry (ROR). */
  rorId?: string[];
  /** A short name or abbreviation of the organization. */
  shortName?: Text[];
  /** Identifier from VIAF (Virtual Authority File). */
  viafId?: string[];
  /** Identifier from Wikidata. */
  wikidataId?: string[];
  $type: "SubtractiveOrganization";
}

/** Rule to prevent publishing of merged organization items. */
export interface WorkflowOrganization {
  /** Targets to which the merged item should NOT be published. */
  forbiddenPublishingTarget?: PublishingTarget[];
  $type: "WorkflowOrganization";
}

/** All fields for a valid organization except for provenance. */
export interface BaseOrganization {
  /** The official name of the organization. */
  officialName: Text[];
  /** An alternative name for the organization */
  alternativeName?: Text[];
  /** Identifier from GEPRIS authority file. */
  geprisId?: string[];
  /** An identifier from the German authority file named Gemeinsame Normdatei (GND), curated by the German National Library (DNB). */
  gndId?: string[];
  /** The ISNI (International Standard Name Identifier) of the organization. */
  isniId?: string[];
  /** An identifier of the Research Organization Registry (ROR). */
  rorId?: string[];
  /** A short name or abbreviation of the organization. */
  shortName?: Text[];
  /** Identifier from VIAF (Virtual Authority File). */
  viafId?: string[];
  /** Identifier from Wikidata. */
  wikidataId?: string[];
}
