// AUTO-GENERATED by mex_form_codegen -- do not edit by hand.
import type { Link, PublishingTarget, Text } from "./shared";

/** Rule to add values to merged organizational units. */
export interface AdditiveOrganizationalUnit {
  /** The described unit is a subunit of another organizational unit. */
  parentUnit?: string;
  /** The official name of the organizational unit. */
  name?: Text[];
  /** An alternative name for the organizational unit. */
  alternativeName?: Text[];
  /** The email address through which the organizational unit can be contacted. */
  email?: string[];
  /** A short name or abbreviation of the organization unit. */
  shortName?: Text[];
  /** Indicates an organization of which this unit is a part, e.g. a department within a larger organization. */
  unitOf?: string[];
  /** A URL serving as the official web presentation of the organizational unit. */
  website?: Link[];
  $type: "AdditiveOrganizationalUnit";
  supersededBy?: string;
}

/** An automatically extracted metadata set describing an organizational unit. */
export interface ExtractedOrganizationalUnit extends BaseOrganizationalUnit {
  /** A primary source for a topic refers to something produced by some agent with direct experience and knowledge about the topic, at the time of the topic's study, without benefit from hindsight. Because of the directness of primary sources, they 'speak for themselves' in ways that cannot be captured through the filter of secondary sources. As such, it is important for secondary sources to reference those primary sources from which they were derived, so that their reliability can be investigated. A primary source relation is a particular case of derivation of secondary materials from their primary sources. It is recognized that the determination of primary sources can be up to interpretation, and should be done according to conventions accepted within the application's domain ([PROV-O, 2013-04-30 ](http://www.w3.org/TR/2013/REC-prov-o-20130430/)). */
  hadPrimarySource: string;
  /** The identifier of the item used in the primary source. */
  identifierInPrimarySource: string;
  $type: "ExtractedOrganizationalUnit";
}

/** The result of merging all extracted items and rules for an organizational unit. */
export interface MergedOrganizationalUnit extends BaseOrganizationalUnit {
  $type: "MergedOrganizationalUnit";
  identifier: string;
  supersededBy?: string;
}

/** Set of rules to create or update an organizational unit item. */
export interface OrganizationalUnitRuleSetRequest {
  additive?: AdditiveOrganizationalUnit;
  subtractive?: SubtractiveOrganizationalUnit;
  preventive?: PreventiveOrganizationalUnit;
  workflow?: WorkflowOrganizationalUnit;
  $type: "OrganizationalUnitRuleSetRequest";
}

/** Set of rules to retrieve an organizational unit item. */
export interface OrganizationalUnitRuleSetResponse {
  additive?: AdditiveOrganizationalUnit;
  subtractive?: SubtractiveOrganizationalUnit;
  preventive?: PreventiveOrganizationalUnit;
  workflow?: WorkflowOrganizationalUnit;
  $type: "OrganizationalUnitRuleSetResponse";
  stableTargetId: string;
}

/** Rule to prevent primary sources for fields of merged organizational units. */
export interface PreventiveOrganizationalUnit {
  $type: "PreventiveOrganizationalUnit";
  alternativeName?: string[];
  email?: string[];
  name?: string[];
  parentUnit?: string[];
  shortName?: string[];
  unitOf?: string[];
  website?: string[];
}

/** Preview for merging all extracted items and rules for an organizational unit. */
export interface PreviewOrganizationalUnit {
  /** The described unit is a subunit of another organizational unit. */
  parentUnit?: string[];
  /** The official name of the organizational unit. */
  name?: Text[];
  /** An alternative name for the organizational unit. */
  alternativeName?: Text[];
  /** The email address through which the organizational unit can be contacted. */
  email?: string[];
  /** A short name or abbreviation of the organization unit. */
  shortName?: Text[];
  /** Indicates an organization of which this unit is a part, e.g. a department within a larger organization. */
  unitOf?: string[];
  /** A URL serving as the official web presentation of the organizational unit. */
  website?: Link[];
  $type: "PreviewOrganizationalUnit";
  identifier: string;
  supersededBy?: string;
}

/** Rule to subtract values from merged organizational units. */
export interface SubtractiveOrganizationalUnit {
  /** The described unit is a subunit of another organizational unit. */
  parentUnit?: string[];
  /** The official name of the organizational unit. */
  name?: Text[];
  /** An alternative name for the organizational unit. */
  alternativeName?: Text[];
  /** The email address through which the organizational unit can be contacted. */
  email?: string[];
  /** A short name or abbreviation of the organization unit. */
  shortName?: Text[];
  /** Indicates an organization of which this unit is a part, e.g. a department within a larger organization. */
  unitOf?: string[];
  /** A URL serving as the official web presentation of the organizational unit. */
  website?: Link[];
  $type: "SubtractiveOrganizationalUnit";
}

/** Rule to prevent publishing of merged organizational unit items. */
export interface WorkflowOrganizationalUnit {
  /** Targets to which the merged item should NOT be published. */
  forbiddenPublishingTarget?: PublishingTarget[];
  $type: "WorkflowOrganizationalUnit";
}

/** All fields for a valid organizational unit except for provenance. */
export interface BaseOrganizationalUnit {
  /** The described unit is a subunit of another organizational unit. */
  parentUnit?: string;
  /** The official name of the organizational unit. */
  name: Text[];
  /** An alternative name for the organizational unit. */
  alternativeName?: Text[];
  /** The email address through which the organizational unit can be contacted. */
  email?: string[];
  /** A short name or abbreviation of the organization unit. */
  shortName?: Text[];
  /** Indicates an organization of which this unit is a part, e.g. a department within a larger organization. */
  unitOf?: string[];
  /** A URL serving as the official web presentation of the organizational unit. */
  website?: Link[];
}
