// AUTO-GENERATED by mex_form_codegen -- do not edit by hand.
import type { PublishingTarget } from "./shared";

/** Rule to add values to merged person items. */
export interface AdditivePerson {
  /** An organization that the described person is affiliated with. */
  affiliation?: string[];
  /** The email address through which the person can be contacted. */
  email?: string[];
  /** The name inherited from the family. */
  familyName?: string[];
  /** The full name of a person. Also used if the naming schema (given name and family name) does not apply to the name. */
  fullName?: string[];
  /** The name given to the person e.g. by their parents. */
  givenName?: string[];
  /** The ISNI (International Standard Name Identifier) of the person. */
  isniId?: string[];
  /** Organizational unit at RKI the person is associated with. */
  memberOf?: string[];
  /** Identifier of a person from the ORCID authority file. */
  orcidId?: string[];
  $type: "AdditivePerson";
  supersededBy?: string;
}

/** An automatically extracted metadata set describing a person. */
export interface ExtractedPerson extends BasePerson {
  /** A primary source for a topic refers to something produced by some agent with direct experience and knowledge about the topic, at the time of the topic's study, without benefit from hindsight. Because of the directness of primary sources, they 'speak for themselves' in ways that cannot be captured through the filter of secondary sources. As such, it is important for secondary sources to reference those primary sources from which they were derived, so that their reliability can be investigated. A primary source relation is a particular case of derivation of secondary materials from their primary sources. It is recognized that the determination of primary sources can be up to interpretation, and should be done according to conventions accepted within the application's domain ([PROV-O, 2013-04-30 ](http://www.w3.org/TR/2013/REC-prov-o-20130430/)). */
  hadPrimarySource: string;
  /** The identifier of the item used in the primary source. */
  identifierInPrimarySource: string;
  $type: "ExtractedPerson";
}

/** The result of merging all extracted items and rules for a person. */
export interface MergedPerson extends BasePerson {
  $type: "MergedPerson";
  identifier: string;
  supersededBy?: string;
}

/** Set of rules to create or update a person item. */
export interface PersonRuleSetRequest {
  additive?: AdditivePerson;
  subtractive?: SubtractivePerson;
  preventive?: PreventivePerson;
  workflow?: WorkflowPerson;
  $type: "PersonRuleSetRequest";
}

/** Set of rules to retrieve a person item. */
export interface PersonRuleSetResponse {
  additive?: AdditivePerson;
  subtractive?: SubtractivePerson;
  preventive?: PreventivePerson;
  workflow?: WorkflowPerson;
  $type: "PersonRuleSetResponse";
  stableTargetId: string;
}

/** Rule to prevent primary sources for fields of merged person items. */
export interface PreventivePerson {
  $type: "PreventivePerson";
  affiliation?: string[];
  email?: string[];
  familyName?: string[];
  fullName?: string[];
  givenName?: string[];
  isniId?: string[];
  memberOf?: string[];
  orcidId?: string[];
}

/** Preview for merging all extracted items and rules for a person. */
export interface PreviewPerson {
  /** An organization that the described person is affiliated with. */
  affiliation?: string[];
  /** The email address through which the person can be contacted. */
  email?: string[];
  /** The name inherited from the family. */
  familyName?: string[];
  /** The full name of a person. Also used if the naming schema (given name and family name) does not apply to the name. */
  fullName?: string[];
  /** The name given to the person e.g. by their parents. */
  givenName?: string[];
  /** The ISNI (International Standard Name Identifier) of the person. */
  isniId?: string[];
  /** Organizational unit at RKI the person is associated with. */
  memberOf?: string[];
  /** Identifier of a person from the ORCID authority file. */
  orcidId?: string[];
  $type: "PreviewPerson";
  identifier: string;
  supersededBy?: string;
}

/** Rule to subtract values from merged person items. */
export interface SubtractivePerson {
  /** An organization that the described person is affiliated with. */
  affiliation?: string[];
  /** The email address through which the person can be contacted. */
  email?: string[];
  /** The name inherited from the family. */
  familyName?: string[];
  /** The full name of a person. Also used if the naming schema (given name and family name) does not apply to the name. */
  fullName?: string[];
  /** The name given to the person e.g. by their parents. */
  givenName?: string[];
  /** The ISNI (International Standard Name Identifier) of the person. */
  isniId?: string[];
  /** Organizational unit at RKI the person is associated with. */
  memberOf?: string[];
  /** Identifier of a person from the ORCID authority file. */
  orcidId?: string[];
  $type: "SubtractivePerson";
}

/** Rule to prevent publishing of merged person items. */
export interface WorkflowPerson {
  /** Targets to which the merged item should NOT be published. */
  forbiddenPublishingTarget?: PublishingTarget[];
  $type: "WorkflowPerson";
}

/** All fields for a valid person except for provenance. */
export interface BasePerson {
  /** An organization that the described person is affiliated with. */
  affiliation?: string[];
  /** The email address through which the person can be contacted. */
  email?: string[];
  /** The name inherited from the family. */
  familyName?: string[];
  /** The full name of a person. Also used if the naming schema (given name and family name) does not apply to the name. */
  fullName?: string[];
  /** The name given to the person e.g. by their parents. */
  givenName?: string[];
  /** The ISNI (International Standard Name Identifier) of the person. */
  isniId?: string[];
  /** Organizational unit at RKI the person is associated with. */
  memberOf?: string[];
  /** Identifier of a person from the ORCID authority file. */
  orcidId?: string[];
}
