// AUTO-GENERATED by mex_form_codegen -- do not edit by hand.
import type { Link, PublishingTarget, Text, Theme } from "./shared";

/** Rule to add values to merged resource items. */
export interface AdditiveResource {
  /** Indicates how access to the resource is restricted. */
  accessRestriction?: AccessRestriction;
  /** The frequency with which items are added to a collection. */
  accrualPeriodicity?: Frequency;
  /** Date of creation of the resource */
  created?: string;
  /** The Digital Object Identifier (DOI) of the resource. */
  doi?: string;
  /** Indicates, if a resource contains data directly or indirectly associated or related to an individual. */
  hasPersonalData?: PersonalData;
  /** A legal document giving official permission to do something with the resource. */
  license?: License;
  /** Specifies the maximum age of the population within the data collection, expressed in years. */
  maxTypicalAge?: number;
  /** Specifies the minimum age of the population within the data collection, expressed in years. */
  minTypicalAge?: number;
  /** Date on which the resource was changed. */
  modified?: string;
  /** The total number of records in the dataset. The number reflects the total data entries (e.g., consultations, prescriptions, lab results, hospital admissions) according to the dataset's content. */
  numberOfRecords?: number;
  /** The number of records for unique individuals represented in the dataset. */
  numberOfUniqueIndividuals?: number;
  /** The size of the underlying data basis, e.g. for studies: the size of the sample. */
  sizeOfDataBasis?: string;
  /** Temporal coverage of the resource. */
  temporal?: string;
  /** Generation is the completion of production of a new entity by an activity. This entity did not exist before generation and becomes available for usage after this generation. */
  wasGeneratedBy?: string;
  /** An agent that serves as a contact for the resource. */
  contact?: string[];
  /** A main category of the resource. A resource can have multiple themes. */
  theme?: Theme[];
  /** The name of the resource. */
  title?: Text[];
  /** This property refers to agents who assume responsibility and accountability for the resource and its appropriate maintenance. */
  unitInCharge?: string[];
  /** A platform from which the resource can be accessed. */
  accessPlatform?: string[];
  /** An alternative name for the resource. */
  alternativeTitle?: Text[];
  /** An analytics distribution of the dataset. */
  analytics?: string[];
  /** Indicates whether the data has been anonymized and/or pseudonymized. */
  anonymizationPseudonymization?: AnonymizationPseudonymization[];
  /** Standards used in the creation, analysis or transmission of the resource. */
  conformsTo?: string[];
  /** An organizational unit of RKI, that is contributing to the resource. */
  contributingUnit?: string[];
  /** A person involved in the creation of the resource. */
  contributor?: string[];
  /** A person responsible for making the resource. */
  creator?: string[];
  /** A text describing the nature of the resource. */
  description?: Text[];
  /** An available distribution of the resource */
  distribution?: string[];
  /** A link to a document documenting the resource. */
  documentation?: Link[];
  /** End date of the temporal coverage of the resource. */
  end?: string[];
  /** An external organization that is somehow involved in the creation of the resource. */
  externalPartner?: string[];
  /** The code values of the respective coding systems that are applied to the dataset, for example code value 'U07.1' as used in the coding system 'ICD-10'. */
  hasCodeValues?: Text[];
  /** The legal basis used to justify processing of personal data. Legal basis (plural: legal bases) are defined by legislations and regulations, whose applicability is usually restricted to specific jurisdictions which can be represented using dpv:hasJurisdiction or dpv:hasLaw. Legal basis can be used without such declarations, e.g. 'Consent', however their interpretation will require association with a law, e.g. 'EU GDPR'. */
  hasLegalBasis?: Text[];
  /** A free text statement of the purpose of the processing of data or personal data. */
  hasPurpose?: Text[];
  /** The category of electronic data for secondary use to which this resource belongs, as described in Article 51 of the Commission Regulation on the European Health Data Space. */
  healthCategory?: HealthCategory[];
  /** A concept from ICD-10. */
  icd10code?: string[];
  /** Instrument, tool, or apparatus used in the research, analysis, observation, or processing of the object that is the subject of this resource. */
  instrumentToolOrApparatus?: Text[];
  /** A related resource, in which the described resource is physically or logically included. */
  isPartOf?: string[];
  /** A keyword or tag describing the resource. */
  keyword?: Text[];
  /** A language of the resource. */
  language?: Language[];
  /** A concept from LOINC. */
  loincId?: string[];
  /** A concept from MeSH. */
  meshId?: string[];
  /** Method used in the research, analysis, observation or processing of the object that is subject to the resource. */
  method?: Text[];
  /** The description of the method, that was used to research, analysis, observation or processing of the object that was subject to the resource. */
  methodDescription?: Text[];
  /** The type of population common to all subjects of the data collection. */
  populationCoverage?: Text[];
  /** A statement about the lineage of a Dataset. Information about how the data was collected, including methodologies, tools, and protocols used. */
  provenance?: Text[];
  /** A publication that deals with the research, analysis, observation or processing of the object that was subject to the resource, e.g. a research paper. */
  publication?: string[];
  /** The entity responsible for making the item available. */
  publisher?: string[];
  /** Some information about the quality of the resource. */
  qualityInformation?: Text[];
  /** A related Resource. */
  relatedResource?: string[];
  /** Method how the resource was created. */
  resourceCreationMethod?: ResourceCreationMethod[];
  /** General type of the resource. */
  resourceTypeGeneral?: ResourceTypeGeneral[];
  /** A term describing the specific nature of the resource. A more precise term than given by the property 'resourceTypeGeneral'. */
  resourceTypeSpecific?: Text[];
  /** Information about rights held in and over the resource as well as rights about the possibilities of the usage of the resource. */
  rights?: Text[];
  /** A sample distribution of the dataset, which can be anonymized or synthetic data, or the data dictionary. */
  sample?: string[];
  /** A related Resource from which the described Resource is derived. */
  source?: string[];
  /** Spatial coverage of the resource. */
  spatial?: Text[];
  /** Start date of the temporal coverage of the resource. */
  start?: string[];
  /** The processing state of the data, e.g. raw or aggregated. */
  stateOfDataProcessing?: DataProcessingState[];
  $type: "AdditiveResource";
  supersededBy?: string;
}

/** An automatically extracted metadata set describing a resource. */
export interface ExtractedResource extends BaseResource {
  /** A primary source for a topic refers to something produced by some agent with direct experience and knowledge about the topic, at the time of the topic's study, without benefit from hindsight. Because of the directness of primary sources, they 'speak for themselves' in ways that cannot be captured through the filter of secondary sources. As such, it is important for secondary sources to reference those primary sources from which they were derived, so that their reliability can be investigated. A primary source relation is a particular case of derivation of secondary materials from their primary sources. It is recognized that the determination of primary sources can be up to interpretation, and should be done according to conventions accepted within the application's domain ([PROV-O, 2013-04-30 ](http://www.w3.org/TR/2013/REC-prov-o-20130430/)). */
  hadPrimarySource: string;
  /** The identifier of the item used in the primary source. */
  identifierInPrimarySource: string;
  $type: "ExtractedResource";
}

/** The result of merging all extracted items and rules for a resource. */
export interface MergedResource extends BaseResource {
  $type: "MergedResource";
  identifier: string;
  supersededBy?: string;
}

/** Rule to prevent primary sources for fields of merged resource items. */
export interface PreventiveResource {
  $type: "PreventiveResource";
  accessPlatform?: string[];
  accessRestriction?: string[];
  accrualPeriodicity?: string[];
  alternativeTitle?: string[];
  analytics?: string[];
  anonymizationPseudonymization?: string[];
  conformsTo?: string[];
  contact?: string[];
  contributingUnit?: string[];
  contributor?: string[];
  created?: string[];
  creator?: string[];
  description?: string[];
  distribution?: string[];
  documentation?: string[];
  doi?: string[];
  end?: string[];
  externalPartner?: string[];
  hasCodeValues?: string[];
  hasLegalBasis?: string[];
  hasPurpose?: string[];
  hasPersonalData?: string[];
  healthCategory?: string[];
  icd10code?: string[];
  instrumentToolOrApparatus?: string[];
  isPartOf?: string[];
  keyword?: string[];
  language?: string[];
  license?: string[];
  loincId?: string[];
  maxTypicalAge?: string[];
  meshId?: string[];
  method?: string[];
  methodDescription?: string[];
  minTypicalAge?: string[];
  modified?: string[];
  numberOfRecords?: string[];
  numberOfUniqueIndividuals?: string[];
  populationCoverage?: string[];
  provenance?: string[];
  publication?: string[];
  publisher?: string[];
  qualityInformation?: string[];
  relatedResource?: string[];
  resourceCreationMethod?: string[];
  resourceTypeGeneral?: string[];
  resourceTypeSpecific?: string[];
  rights?: string[];
  sample?: string[];
  source?: string[];
  sizeOfDataBasis?: string[];
  start?: string[];
  spatial?: string[];
  stateOfDataProcessing?: string[];
  temporal?: string[];
  theme?: string[];
  title?: string[];
  unitInCharge?: string[];
  wasGeneratedBy?: string[];
}

/** Preview for merging all extracted items and rules for a resource. */
export interface PreviewResource {
  /** Indicates how access to the resource is restricted. */
  accessRestriction?: AccessRestriction[];
  /** The frequency with which items are added to a collection. */
  accrualPeriodicity?: Frequency[];
  /** Date of creation of the resource */
  created?: string[];
  /** The Digital Object Identifier (DOI) of the resource. */
  doi?: string[];
  /** Indicates, if a resource contains data directly or indirectly associated or related to an individual. */
  hasPersonalData?: PersonalData[];
  /** A legal document giving official permission to do something with the resource. */
  license?: License[];
  /** Specifies the maximum age of the population within the data collection, expressed in years. */
  maxTypicalAge?: number[];
  /** Specifies the minimum age of the population within the data collection, expressed in years. */
  minTypicalAge?: number[];
  /** Date on which the resource was changed. */
  modified?: string[];
  /** The total number of records in the dataset. The number reflects the total data entries (e.g., consultations, prescriptions, lab results, hospital admissions) according to the dataset's content. */
  numberOfRecords?: number[];
  /** The number of records for unique individuals represented in the dataset. */
  numberOfUniqueIndividuals?: number[];
  /** The size of the underlying data basis, e.g. for studies: the size of the sample. */
  sizeOfDataBasis?: string[];
  /** Temporal coverage of the resource. */
  temporal?: string[];
  /** Generation is the completion of production of a new entity by an activity. This entity did not exist before generation and becomes available for usage after this generation. */
  wasGeneratedBy?: string[];
  /** An agent that serves as a contact for the resource. */
  contact?: string[];
  /** A main category of the resource. A resource can have multiple themes. */
  theme?: Theme[];
  /** The name of the resource. */
  title?: Text[];
  /** This property refers to agents who assume responsibility and accountability for the resource and its appropriate maintenance. */
  unitInCharge?: string[];
  /** A platform from which the resource can be accessed. */
  accessPlatform?: string[];
  /** An alternative name for the resource. */
  alternativeTitle?: Text[];
  /** An analytics distribution of the dataset. */
  analytics?: string[];
  /** Indicates whether the data has been anonymized and/or pseudonymized. */
  anonymizationPseudonymization?: AnonymizationPseudonymization[];
  /** Standards used in the creation, analysis or transmission of the resource. */
  conformsTo?: string[];
  /** An organizational unit of RKI, that is contributing to the resource. */
  contributingUnit?: string[];
  /** A person involved in the creation of the resource. */
  contributor?: string[];
  /** A person responsible for making the resource. */
  creator?: string[];
  /** A text describing the nature of the resource. */
  description?: Text[];
  /** An available distribution of the resource */
  distribution?: string[];
  /** A link to a document documenting the resource. */
  documentation?: Link[];
  /** End date of the temporal coverage of the resource. */
  end?: string[];
  /** An external organization that is somehow involved in the creation of the resource. */
  externalPartner?: string[];
  /** The code values of the respective coding systems that are applied to the dataset, for example code value 'U07.1' as used in the coding system 'ICD-10'. */
  hasCodeValues?: Text[];
  /** The legal basis used to justify processing of personal data. Legal basis (plural: legal bases) are defined by legislations and regulations, whose applicability is usually restricted to specific jurisdictions which can be represented using dpv:hasJurisdiction or dpv:hasLaw. Legal basis can be used without such declarations, e.g. 'Consent', however their interpretation will require association with a law, e.g. 'EU GDPR'. */
  hasLegalBasis?: Text[];
  /** A free text statement of the purpose of the processing of data or personal data. */
  hasPurpose?: Text[];
  /** The category of electronic data for secondary use to which this resource belongs, as described in Article 51 of the Commission Regulation on the European Health Data Space. */
  healthCategory?: HealthCategory[];
  /** A concept from ICD-10. */
  icd10code?: string[];
  /** Instrument, tool, or apparatus used in the research, analysis, observation, or processing of the object that is the subject of this resource. */
  instrumentToolOrApparatus?: Text[];
  /** A related resource, in which the described resource is physically or logically included. */
  isPartOf?: string[];
  /** A keyword or tag describing the resource. */
  keyword?: Text[];
  /** A language of the resource. */
  language?: Language[];
  /** A concept from LOINC. */
  loincId?: string[];
  /** A concept from MeSH. */
  meshId?: string[];
  /** Method used in the research, analysis, observation or processing of the object that is subject to the resource. */
  method?: Text[];
  /** The description of the method, that was used to research, analysis, observation or processing of the object that was subject to the resource. */
  methodDescription?: Text[];
  /** The type of population common to all subjects of the data collection. */
  populationCoverage?: Text[];
  /** A statement about the lineage of a Dataset. Information about how the data was collected, including methodologies, tools, and protocols used. */
  provenance?: Text[];
  /** A publication that deals with the research, analysis, observation or processing of the object that was subject to the resource, e.g. a research paper. */
  publication?: string[];
  /** The entity responsible for making the item available. */
  publisher?: string[];
  /** Some information about the quality of the resource. */
  qualityInformation?: Text[];
  /** A related Resource. */
  relatedResource?: string[];
  /** Method how the resource was created. */
  resourceCreationMethod?: ResourceCreationMethod[];
  /** General type of the resource. */
  resourceTypeGeneral?: ResourceTypeGeneral[];
  /** A term describing the specific nature of the resource. A more precise term than given by the property 'resourceTypeGeneral'. */
  resourceTypeSpecific?: Text[];
  /** Information about rights held in and over the resource as well as rights about the possibilities of the usage of the resource. */
  rights?: Text[];
  /** A sample distribution of the dataset, which can be anonymized or synthetic data, or the data dictionary. */
  sample?: string[];
  /** A related Resource from which the described Resource is derived. */
  source?: string[];
  /** Spatial coverage of the resource. */
  spatial?: Text[];
  /** Start date of the temporal coverage of the resource. */
  start?: string[];
  /** The processing state of the data, e.g. raw or aggregated. */
  stateOfDataProcessing?: DataProcessingState[];
  $type: "PreviewResource";
  identifier: string;
  supersededBy?: string;
}

/** Set of rules to create or update a resource item. */
export interface ResourceRuleSetRequest {
  additive?: AdditiveResource;
  subtractive?: SubtractiveResource;
  preventive?: PreventiveResource;
  workflow?: WorkflowResource;
  $type: "ResourceRuleSetRequest";
}

/** Set of rules to retrieve a resource item. */
export interface ResourceRuleSetResponse {
  additive?: AdditiveResource;
  subtractive?: SubtractiveResource;
  preventive?: PreventiveResource;
  workflow?: WorkflowResource;
  $type: "ResourceRuleSetResponse";
  stableTargetId: string;
}

/** Rule to subtract values from merged resource items. */
export interface SubtractiveResource {
  /** Indicates how access to the resource is restricted. */
  accessRestriction?: AccessRestriction[];
  /** The frequency with which items are added to a collection. */
  accrualPeriodicity?: Frequency[];
  /** Date of creation of the resource */
  created?: string[];
  /** The Digital Object Identifier (DOI) of the resource. */
  doi?: string[];
  /** Indicates, if a resource contains data directly or indirectly associated or related to an individual. */
  hasPersonalData?: PersonalData[];
  /** A legal document giving official permission to do something with the resource. */
  license?: License[];
  /** Specifies the maximum age of the population within the data collection, expressed in years. */
  maxTypicalAge?: number[];
  /** Specifies the minimum age of the population within the data collection, expressed in years. */
  minTypicalAge?: number[];
  /** Date on which the resource was changed. */
  modified?: string[];
  /** The total number of records in the dataset. The number reflects the total data entries (e.g., consultations, prescriptions, lab results, hospital admissions) according to the dataset's content. */
  numberOfRecords?: number[];
  /** The number of records for unique individuals represented in the dataset. */
  numberOfUniqueIndividuals?: number[];
  /** The size of the underlying data basis, e.g. for studies: the size of the sample. */
  sizeOfDataBasis?: string[];
  /** Temporal coverage of the resource. */
  temporal?: string[];
  /** Generation is the completion of production of a new entity by an activity. This entity did not exist before generation and becomes available for usage after this generation. */
  wasGeneratedBy?: string[];
  /** An agent that serves as a contact for the resource. */
  contact?: string[];
  /** A main category of the resource. A resource can have multiple themes. */
  theme?: Theme[];
  /** The name of the resource. */
  title?: Text[];
  /** This property refers to agents who assume responsibility and accountability for the resource and its appropriate maintenance. */
  unitInCharge?: string[];
  /** A platform from which the resource can be accessed. */
  accessPlatform?: string[];
  /** An alternative name for the resource. */
  alternativeTitle?: Text[];
  /** An analytics distribution of the dataset. */
  analytics?: string[];
  /** Indicates whether the data has been anonymized and/or pseudonymized. */
  anonymizationPseudonymization?: AnonymizationPseudonymization[];
  /** Standards used in the creation, analysis or transmission of the resource. */
  conformsTo?: string[];
  /** An organizational unit of RKI, that is contributing to the resource. */
  contributingUnit?: string[];
  /** A person involved in the creation of the resource. */
  contributor?: string[];
  /** A person responsible for making the resource. */
  creator?: string[];
  /** A text describing the nature of the resource. */
  description?: Text[];
  /** An available distribution of the resource */
  distribution?: string[];
  /** A link to a document documenting the resource. */
  documentation?: Link[];
  /** End date of the temporal coverage of the resource. */
  end?: string[];
  /** An external organization that is somehow involved in the creation of the resource. */
  externalPartner?: string[];
  /** The code values of the respective coding systems that are applied to the dataset, for example code value 'U07.1' as used in the coding system 'ICD-10'. */
  hasCodeValues?: Text[];
  /** The legal basis used to justify processing of personal data. Legal basis (plural: legal bases) are defined by legislations and regulations, whose applicability is usually restricted to specific jurisdictions which can be represented using dpv:hasJurisdiction or dpv:hasLaw. Legal basis can be used without such declarations, e.g. 'Consent', however their interpretation will require association with a law, e.g. 'EU GDPR'. */
  hasLegalBasis?: Text[];
  /** A free text statement of the purpose of the processing of data or personal data. */
  hasPurpose?: Text[];
  /** The category of electronic data for secondary use to which this resource belongs, as described in Article 51 of the Commission Regulation on the European Health Data Space. */
  healthCategory?: HealthCategory[];
  /** A concept from ICD-10. */
  icd10code?: string[];
  /** Instrument, tool, or apparatus used in the research, analysis, observation, or processing of the object that is the subject of this resource. */
  instrumentToolOrApparatus?: Text[];
  /** A related resource, in which the described resource is physically or logically included. */
  isPartOf?: string[];
  /** A keyword or tag describing the resource. */
  keyword?: Text[];
  /** A language of the resource. */
  language?: Language[];
  /** A concept from LOINC. */
  loincId?: string[];
  /** A concept from MeSH. */
  meshId?: string[];
  /** Method used in the research, analysis, observation or processing of the object that is subject to the resource. */
  method?: Text[];
  /** The description of the method, that was used to research, analysis, observation or processing of the object that was subject to the resource. */
  methodDescription?: Text[];
  /** The type of population common to all subjects of the data collection. */
  populationCoverage?: Text[];
  /** A statement about the lineage of a Dataset. Information about how the data was collected, including methodologies, tools, and protocols used. */
  provenance?: Text[];
  /** A publication that deals with the research, analysis, observation or processing of the object that was subject to the resource, e.g. a research paper. */
  publication?: string[];
  /** The entity responsible for making the item available. */
  publisher?: string[];
  /** Some information about the quality of the resource. */
  qualityInformation?: Text[];
  /** A related Resource. */
  relatedResource?: string[];
  /** Method how the resource was created. */
  resourceCreationMethod?: ResourceCreationMethod[];
  /** General type of the resource. */
  resourceTypeGeneral?: ResourceTypeGeneral[];
  /** A term describing the specific nature of the resource. A more precise term than given by the property 'resourceTypeGeneral'. */
  resourceTypeSpecific?: Text[];
  /** Information about rights held in and over the resource as well as rights about the possibilities of the usage of the resource. */
  rights?: Text[];
  /** A sample distribution of the dataset, which can be anonymized or synthetic data, or the data dictionary. */
  sample?: string[];
  /** A related Resource from which the described Resource is derived. */
  source?: string[];
  /** Spatial coverage of the resource. */
  spatial?: Text[];
  /** Start date of the temporal coverage of the resource. */
  start?: string[];
  /** The processing state of the data, e.g. raw or aggregated. */
  stateOfDataProcessing?: DataProcessingState[];
  $type: "SubtractiveResource";
}

/** Rule to prevent publishing of merged resource items. */
export interface WorkflowResource {
  /** Targets to which the merged item should NOT be published. */
  forbiddenPublishingTarget?: PublishingTarget[];
  $type: "WorkflowResource";
}

/** The access restriction type. */
export type AccessRestriction = "https://mex.rki.de/item/access-restriction-1" | "https://mex.rki.de/item/access-restriction-2";

/** Whether the resource is anonymized/pseudonymized. */
export type AnonymizationPseudonymization = "https://mex.rki.de/item/anonymization-pseudonymization-1" | "https://mex.rki.de/item/anonymization-pseudonymization-2";

/** All fields for a valid resource except for provenance. */
export interface BaseResource {
  /** Indicates how access to the resource is restricted. */
  accessRestriction: AccessRestriction;
  /** The frequency with which items are added to a collection. */
  accrualPeriodicity?: Frequency;
  /** Date of creation of the resource */
  created?: string;
  /** The Digital Object Identifier (DOI) of the resource. */
  doi?: string;
  /** Indicates, if a resource contains data directly or indirectly associated or related to an individual. */
  hasPersonalData?: PersonalData;
  /** A legal document giving official permission to do something with the resource. */
  license?: License;
  /** Specifies the maximum age of the population within the data collection, expressed in years. */
  maxTypicalAge?: number;
  /** Specifies the minimum age of the population within the data collection, expressed in years. */
  minTypicalAge?: number;
  /** Date on which the resource was changed. */
  modified?: string;
  /** The total number of records in the dataset. The number reflects the total data entries (e.g., consultations, prescriptions, lab results, hospital admissions) according to the dataset's content. */
  numberOfRecords?: number;
  /** The number of records for unique individuals represented in the dataset. */
  numberOfUniqueIndividuals?: number;
  /** The size of the underlying data basis, e.g. for studies: the size of the sample. */
  sizeOfDataBasis?: string;
  /** Temporal coverage of the resource. */
  temporal?: string;
  /** Generation is the completion of production of a new entity by an activity. This entity did not exist before generation and becomes available for usage after this generation. */
  wasGeneratedBy?: string;
  /** An agent that serves as a contact for the resource. */
  contact: string[];
  /** A main category of the resource. A resource can have multiple themes. */
  theme: Theme[];
  /** The name of the resource. */
  title: Text[];
  /** This property refers to agents who assume responsibility and accountability for the resource and its appropriate maintenance. */
  unitInCharge: string[];
  /** A platform from which the resource can be accessed. */
  accessPlatform?: string[];
  /** An alternative name for the resource. */
  alternativeTitle?: Text[];
  /** An analytics distribution of the dataset. */
  analytics?: string[];
  /** Indicates whether the data has been anonymized and/or pseudonymized. */
  anonymizationPseudonymization?: AnonymizationPseudonymization[];
  /** Standards used in the creation, analysis or transmission of the resource. */
  conformsTo?: string[];
  /** An organizational unit of RKI, that is contributing to the resource. */
  contributingUnit?: string[];
  /** A person involved in the creation of the resource. */
  contributor?: string[];
  /** A person responsible for making the resource. */
  creator?: string[];
  /** A text describing the nature of the resource. */
  description?: Text[];
  /** An available distribution of the resource */
  distribution?: string[];
  /** A link to a document documenting the resource. */
  documentation?: Link[];
  /** End date of the temporal coverage of the resource. */
  end?: string[];
  /** An external organization that is somehow involved in the creation of the resource. */
  externalPartner?: string[];
  /** The code values of the respective coding systems that are applied to the dataset, for example code value 'U07.1' as used in the coding system 'ICD-10'. */
  hasCodeValues?: Text[];
  /** The legal basis used to justify processing of personal data. Legal basis (plural: legal bases) are defined by legislations and regulations, whose applicability is usually restricted to specific jurisdictions which can be represented using dpv:hasJurisdiction or dpv:hasLaw. Legal basis can be used without such declarations, e.g. 'Consent', however their interpretation will require association with a law, e.g. 'EU GDPR'. */
  hasLegalBasis?: Text[];
  /** A free text statement of the purpose of the processing of data or personal data. */
  hasPurpose?: Text[];
  /** The category of electronic data for secondary use to which this resource belongs, as described in Article 51 of the Commission Regulation on the European Health Data Space. */
  healthCategory?: HealthCategory[];
  /** A concept from ICD-10. */
  icd10code?: string[];
  /** Instrument, tool, or apparatus used in the research, analysis, observation, or processing of the object that is the subject of this resource. */
  instrumentToolOrApparatus?: Text[];
  /** A related resource, in which the described resource is physically or logically included. */
  isPartOf?: string[];
  /** A keyword or tag describing the resource. */
  keyword?: Text[];
  /** A language of the resource. */
  language?: Language[];
  /** A concept from LOINC. */
  loincId?: string[];
  /** A concept from MeSH. */
  meshId?: string[];
  /** Method used in the research, analysis, observation or processing of the object that is subject to the resource. */
  method?: Text[];
  /** The description of the method, that was used to research, analysis, observation or processing of the object that was subject to the resource. */
  methodDescription?: Text[];
  /** The type of population common to all subjects of the data collection. */
  populationCoverage?: Text[];
  /** A statement about the lineage of a Dataset. Information about how the data was collected, including methodologies, tools, and protocols used. */
  provenance?: Text[];
  /** A publication that deals with the research, analysis, observation or processing of the object that was subject to the resource, e.g. a research paper. */
  publication?: string[];
  /** The entity responsible for making the item available. */
  publisher?: string[];
  /** Some information about the quality of the resource. */
  qualityInformation?: Text[];
  /** A related Resource. */
  relatedResource?: string[];
  /** Method how the resource was created. */
  resourceCreationMethod?: ResourceCreationMethod[];
  /** General type of the resource. */
  resourceTypeGeneral?: ResourceTypeGeneral[];
  /** A term describing the specific nature of the resource. A more precise term than given by the property 'resourceTypeGeneral'. */
  resourceTypeSpecific?: Text[];
  /** Information about rights held in and over the resource as well as rights about the possibilities of the usage of the resource. */
  rights?: Text[];
  /** A sample distribution of the dataset, which can be anonymized or synthetic data, or the data dictionary. */
  sample?: string[];
  /** A related Resource from which the described Resource is derived. */
  source?: string[];
  /** Spatial coverage of the resource. */
  spatial?: Text[];
  /** Start date of the temporal coverage of the resource. */
  start?: string[];
  /** The processing state of the data, e.g. raw or aggregated. */
  stateOfDataProcessing?: DataProcessingState[];
}

/** Type for state of data processing. */
export type DataProcessingState = "https://mex.rki.de/item/data-processing-state-1" | "https://mex.rki.de/item/data-processing-state-2" | "https://mex.rki.de/item/data-processing-state-3" | "https://mex.rki.de/item/data-processing-state-4" | "https://mex.rki.de/item/data-processing-state-5";

/** Frequency type. */
export type Frequency = "https://mex.rki.de/item/frequency-1" | "https://mex.rki.de/item/frequency-2" | "https://mex.rki.de/item/frequency-3" | "https://mex.rki.de/item/frequency-4" | "https://mex.rki.de/item/frequency-5" | "https://mex.rki.de/item/frequency-6" | "https://mex.rki.de/item/frequency-7" | "https://mex.rki.de/item/frequency-8" | "https://mex.rki.de/item/frequency-9" | "https://mex.rki.de/item/frequency-10" | "https://mex.rki.de/item/frequency-11" | "https://mex.rki.de/item/frequency-12" | "https://mex.rki.de/item/frequency-13" | "https://mex.rki.de/item/frequency-14" | "https://mex.rki.de/item/frequency-15" | "https://mex.rki.de/item/frequency-16" | "https://mex.rki.de/item/frequency-17";

/** Type for health category. */
export type HealthCategory = "https://mex.rki.de/item/health-category-1" | "https://mex.rki.de/item/health-category-2" | "https://mex.rki.de/item/health-category-3" | "https://mex.rki.de/item/health-category-4" | "https://mex.rki.de/item/health-category-5" | "https://mex.rki.de/item/health-category-6" | "https://mex.rki.de/item/health-category-7" | "https://mex.rki.de/item/health-category-8" | "https://mex.rki.de/item/health-category-9" | "https://mex.rki.de/item/health-category-10" | "https://mex.rki.de/item/health-category-11" | "https://mex.rki.de/item/health-category-12" | "https://mex.rki.de/item/health-category-13" | "https://mex.rki.de/item/health-category-14" | "https://mex.rki.de/item/health-category-15" | "https://mex.rki.de/item/health-category-16" | "https://mex.rki.de/item/health-category-17";

/** Language type. */
export type Language = "https://mex.rki.de/item/language-1" | "https://mex.rki.de/item/language-2" | "https://mex.rki.de/item/language-3" | "https://mex.rki.de/item/language-4" | "https://mex.rki.de/item/language-5";

/** License type. */
export type License = "https://mex.rki.de/item/license-1";

/** Classification of personal data. */
export type PersonalData = "https://mex.rki.de/item/personal-data-1" | "https://mex.rki.de/item/personal-data-2";

/** The creation method of a resource. */
export type ResourceCreationMethod = "https://mex.rki.de/item/resource-creation-method-1" | "https://mex.rki.de/item/resource-creation-method-2" | "https://mex.rki.de/item/resource-creation-method-3" | "https://mex.rki.de/item/resource-creation-method-4" | "https://mex.rki.de/item/resource-creation-method-5" | "https://mex.rki.de/item/resource-creation-method-6" | "https://mex.rki.de/item/resource-creation-method-7";

/** The general type of a resource. */
export type ResourceTypeGeneral = "https://mex.rki.de/item/resource-type-general-2" | "https://mex.rki.de/item/resource-type-general-13" | "https://mex.rki.de/item/resource-type-general-14" | "https://mex.rki.de/item/resource-type-general-15" | "https://mex.rki.de/item/resource-type-general-16" | "https://mex.rki.de/item/resource-type-general-17" | "https://mex.rki.de/item/resource-type-general-18";
