// AUTO-GENERATED by mex_form_codegen -- do not edit by hand.

/** Type class for Link objects. Links can be parsed from nested JSON objects or from raw strings. Example: Link(url="http://foo.bar") == Link.model_validate("http://foo.bar") */
export interface Link {
  language?: LinkLanguage;
  title?: string;
  url: string;
}

/** Possible language tags for `Link` values. */
export type LinkLanguage = "de" | "en" | "fr" | "es" | "ru";

/** Possible targets to which a merged item could be published. */
export type PublishingTarget = "invenio" | "datenkompass";

/** Type class for text objects. Texts can be parsed from nested JSON objects or from raw strings. Example: Text(value="foo") == Text.model_validate("foo") */
export interface Text {
  value: string;
  language?: TextLanguage;
}

/** Possible language tags for `Text` values. */
export type TextLanguage = "de" | "en" | "fr" | "es" | "ru";

/** The theme type. */
export type Theme =
  | "https://mex.rki.de/item/theme-1"
  | "https://mex.rki.de/item/theme-11"
  | "https://mex.rki.de/item/theme-20"
  | "https://mex.rki.de/item/theme-21"
  | "https://mex.rki.de/item/theme-22"
  | "https://mex.rki.de/item/theme-23"
  | "https://mex.rki.de/item/theme-24"
  | "https://mex.rki.de/item/theme-25"
  | "https://mex.rki.de/item/theme-36"
  | "https://mex.rki.de/item/theme-37";
