name: Linting

on:
  push:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
              ${{ env.cache-name }}-

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install requirements
        run: make install

      - name: Run linters
        run: make linter
